import type { IdeiaDeProjeto } from "./tipos";

export const PROJETOS_INTERMEDIARIOS: IdeiaDeProjeto[] = [
  {
    slug: "limitador-de-taxa-quatro-algoritmos",
    titulo: "Limitador de taxa: quatro algoritmos, um benchmark honesto",
    gancho: "Implemente token bucket, leaky bucket, janela fixa e janela deslizante, e descubra com dados qual escolher em cada situação.",
    nivel: "Intermediário",
    area: "backend",
    tempo: "3 a 4 semanas",
    problema: "Quase todo tutorial ensina um limitador de taxa e para por aí. Em produção, a pergunta é qual algoritmo usar, e a resposta depende de rajadas, justiça entre clientes e custo de memória. Comparar com medição, em vez de repetir a recomendação de um blog, é o tipo de raciocínio que a área valoriza.",
    construir: [
      "Os quatro algoritmos em uma interface comum, em memória e com uma versão distribuída em Redis (com operações atômicas).",
      "Um gerador de carga que simula clientes bem-comportados, clientes em rajada e um cliente abusivo.",
      "Testes de concorrência que provam que o limite não é ultrapassado com muitas threads ou processos.",
      "Um relatório com gráficos: requisições aceitas, atrasos, memória usada e justiça entre clientes em cada algoritmo.",
    ],
    diferencial: [
      "A falha na janela fixa mostrada na prática: o dobro do limite passando na virada de janela, com um gráfico que convence.",
      "Uma recomendação por cenário (API pública, login, processamento em lote) com a justificativa baseada nos seus números.",
      "Um cabeçalho de resposta padronizado com o limite restante e o tempo de espera, e um cliente exemplo que respeita.",
    ],
    entregaveis: [
      "O repositório com as quatro implementações, os testes de concorrência e o gerador de carga.",
      "O relatório com gráficos e a recomendação por cenário.",
      "Instruções para reproduzir os benchmarks em uma máquina qualquer.",
    ],
    comoSerVisto: [
      "O gráfico da janela fixa estourando o limite é um conteúdo compartilhável por si só: publique com uma explicação de um parágrafo.",
      "Escreva o relatório como um texto de engenharia, com perguntas, hipóteses e resultados, e não como um tutorial.",
      "Envie o resultado a uma lista ou comunidade de back-end pedindo a crítica da metodologia.",
    ],
    sinalNaCarreira: "Osmani recomenda dominar fundamentos e comparar abordagens em vez de apenas aplicá-las. Medir algoritmos sob concorrência mostra raciocínio de engenharia e conforto com complexidade, o que continua sendo o que separa quem entende da pessoa que só consegue pedir a uma IA.",
    habilidades: ["Algoritmos e complexidade", "Concorrência", "Benchmarks", "Redis"],
    tecnologias: ["Python, TypeScript ou Go", "Redis", "Uma biblioteca de gráficos"],
    evidencias: ["osmani-2026", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Assíncrono em Node", href: "/aprenda/typescript/assincrono-em-node" },
      { rotulo: "Funcional e iteradores", href: "/aprenda/python/funcional-e-iteradores" },
    ],
  },
  {
    slug: "avaliacao-de-ia-com-dados-proprios",
    titulo: "Avaliação de um assistente de IA com os seus próprios testes",
    gancho: "Em vez de mais um chatbot, construa o conjunto de testes que diz se um modelo resolve bem uma tarefa real, e compare opções com números.",
    nivel: "Intermediário",
    area: "dados-ia",
    tempo: "3 a 4 semanas",
    problema: "A maioria dos portfólios de IA é um chatbot que 'responde perguntas'. O que as equipes não têm, e precisam, é a pergunta anterior: o quanto esse sistema acerta, onde falha e se uma mudança de modelo ou de prompt melhorou ou piorou. Segundo o Stack Overflow 2025, 46% desconfiam da precisão da IA e 66% se frustram com respostas quase certas. Saber medir é a resposta a esse problema.",
    construir: [
      "Escolha uma tarefa real e delimitada (classificar mensagens de suporte, extrair campos de e-mails, resumir changelogs) e construa um conjunto de pelo menos 100 exemplos com a resposta esperada, rotulados por você, incluindo casos difíceis.",
      "Um avaliador automático: roda o sistema em todos os exemplos e calcula métricas adequadas à tarefa (acerto, precisão e revocação, ou uma nota por critério).",
      "Compare pelo menos três variações (modelos ou prompts diferentes) em acerto, custo e tempo de resposta.",
      "Analise os erros: agrupe as falhas em categorias e descreva o padrão.",
    ],
    diferencial: [
      "Rode o avaliador no CI: uma mudança de prompt que piora a métrica falha o build, como um teste de regressão.",
      "Meça a variação entre execuções repetidas e não confie em uma só.",
      "Se usar um modelo como juiz, valide o juiz contra os seus rótulos humanos e informe o quanto ele concorda.",
    ],
    entregaveis: [
      "O conjunto de dados de avaliação, com a descrição de como foi construído e rotulado.",
      "O avaliador e o relatório comparativo com custo, tempo e erros agrupados.",
      "O texto com a conclusão: qual variação escolher para esta tarefa e por quê.",
    ],
    comoSerVisto: [
      "Publique o conjunto de dados (se não houver informação sensível): quem trabalha com IA procura conjuntos de avaliação e cita quem os cria.",
      "Escreva sobre um erro surpreendente do modelo, com o exemplo: é o tipo de texto que circula entre profissionais.",
      "Mostre o gráfico de regressão do CI: é uma imagem curta de rigor.",
    ],
    sinalNaCarreira: "O Octoverse mostra mais de 1,1 milhão de repositórios importando SDKs de modelos de linguagem, então usar a API deixou de ser diferencial, e medir se funciona é o que falta. Osmani recomenda justamente um portfólio de IA que mostre como o resultado foi verificado.",
    habilidades: ["Avaliação de modelos", "Métricas", "Análise de erros", "Testes de regressão", "Custo e latência"],
    tecnologias: ["Python", "A API de um ou mais modelos", "pytest", "GitHub Actions"],
    evidencias: ["stackoverflow-2025", "osmani-2026", "octoverse-2025"],
    estudarNoKoda: [
      { rotulo: "Avaliando sistemas com LLM", href: "/aprenda/llm-mcp-mvp/avaliando-sistemas-com-llm" },
      { rotulo: "API, ferramentas e segurança", href: "/aprenda/llm-mcp-mvp/api-ferramentas-e-seguranca" },
    ],
    cuidado: "Não envie a modelos externos dados pessoais ou confidenciais. Use dados sintéticos ou anonimizados.",
  },
  {
    slug: "infraestrutura-como-codigo-com-orcamento",
    titulo: "Infraestrutura como código com orçamento e botão de destruir",
    gancho: "Provisione uma aplicação em três camadas na nuvem por código, com o custo estimado antes do deploy e a destruição garantida depois.",
    nivel: "Intermediário",
    area: "nuvem-devops",
    tempo: "3 a 4 semanas",
    problema: "Quem aprende nuvem no console clica e esquece. Quem trabalha com nuvem escreve a infraestrutura em código, estima o custo antes e desliga o que não usa. O medo de uma conta inesperada afasta muita gente, e um projeto que demonstra controle de custo transforma esse medo em habilidade visível.",
    construir: [
      "Uma aplicação simples em três camadas (front, API e banco) descrita por inteiro em código (Terraform ou CDK), em uma rede com sub-redes públicas e privadas e permissões mínimas.",
      "Uma estimativa de custo mensal calculada antes do deploy, exibida no pull request.",
      "Alarmes de orçamento e um comando que destrói tudo, com verificação de que nada sobrou cobrando.",
      "Um diagrama da arquitetura, gerado ou desenhado, e a justificativa das escolhas de rede e de permissões.",
    ],
    diferencial: [
      "Um ambiente de pré-visualização por pull request que se desfaz sozinho ao fechar o PR.",
      "Verificações de segurança da infraestrutura no CI (buckets públicos, portas abertas, permissões amplas).",
      "Um relatório do custo real de um mês de uso, comparado com a estimativa.",
    ],
    entregaveis: [
      "O repositório com a infraestrutura em código, o pipeline e a documentação.",
      "O diagrama e o texto de decisões.",
      "O relatório de custo estimado versus real.",
    ],
    comoSerVisto: [
      "Mostre o número: 'aplicação completa por X reais por mês e destruída em um comando' é uma frase que atrai atenção.",
      "Escreva sobre um erro de configuração que você cometeu e como o CI o pegou.",
      "Se estuda para uma certificação, registre o projeto como o laboratório que aplica os conceitos.",
    ],
    sinalNaCarreira: "A Brasscom aponta a computação em nuvem entre as maiores demandas do mercado brasileiro e a pesquisa da ISC2 lista segurança em nuvem entre as maiores lacunas de habilidade. Mostrar a nuvem sob controle de custo e de permissões responde às duas coisas.",
    habilidades: ["Infraestrutura como código", "Redes em nuvem", "Permissões mínimas", "Controle de custos"],
    tecnologias: ["Terraform ou AWS CDK", "AWS (ou outra nuvem)", "GitHub Actions"],
    evidencias: ["brasscom", "isc2-2024", "dora"],
    estudarNoKoda: [
      { rotulo: "Trilha AWS Cloud Practitioner", href: "/aprenda/aws-cloud-practitioner" },
      { rotulo: "Redes: VPC, Route 53 e CloudFront", href: "/aprenda/aws-cloud-practitioner/redes-vpc-route-53-e-cloudfront" },
    ],
    cuidado: "Defina um alarme de orçamento antes de criar qualquer recurso e use sempre uma conta de estudo separada.",
  },
  {
    slug: "pre-commit-de-segredos-medido",
    titulo: "Detector de segredos com taxa de falso positivo medida",
    gancho: "Construa um verificador de segredos para o pré-commit e prove com números quantos vazamentos ele pega e quantos alarmes falsos ele gera.",
    nivel: "Intermediário",
    area: "seguranca",
    tempo: "3 semanas",
    problema: "Ferramentas de detecção de segredos existem, mas todo time as desliga em algum momento por excesso de alarmes falsos. O desafio de engenharia não é achar padrões, e sim equilibrar sensibilidade e ruído. Medir esse equilíbrio, em vez de afirmar que 'funciona', é o que diferencia uma ferramenta usada de uma abandonada.",
    construir: [
      "Um verificador que examina o que está para ser commitado, com regras por padrão (formatos de chaves conhecidas) e por entropia (textos aleatórios longos).",
      "Um conjunto de testes rotulado: exemplos que são segredos (fictícios, no formato de verdade) e exemplos que não são, incluindo os difíceis (hashes de commits, identificadores, textos em Base64).",
      "As métricas: precisão e revocação, e como mudam com o limiar de entropia.",
      "Um arquivo de exceções versionado, com justificativa obrigatória para cada item ignorado.",
    ],
    diferencial: [
      "Rode o verificador no histórico de dez repositórios públicos pequenos e analise os resultados (sem divulgar nenhum segredo encontrado).",
      "Um modo que, ao encontrar um segredo, mostra o roteiro de resposta: revogar, investigar, limpar.",
      "Um gráfico do compromisso entre precisão e revocação, com o ponto que você escolheu e o porquê.",
    ],
    entregaveis: [
      "O verificador instalável como gancho de pré-commit, com testes.",
      "O conjunto rotulado e o relatório de precisão e revocação.",
      "O guia de resposta a vazamentos.",
    ],
    comoSerVisto: [
      "O gráfico de precisão e revocação é uma imagem que engenheiros de segurança entendem à primeira vista.",
      "Escreva sobre o falso positivo mais curioso que encontrou.",
      "Publique o conjunto rotulado: ele ajuda outras pessoas a testarem suas ferramentas, e quem usa cita.",
    ],
    sinalNaCarreira: "Mostra segurança aplicada e rigor de medição. O DBIR 2026 coloca vulnerabilidades e credenciais entre as principais portas de entrada de invasões, e a ISC2 lista segurança de aplicações entre as maiores lacunas de habilidade. Saber lidar com o equilíbrio entre proteção e usabilidade é o que times de segurança mais procuram.",
    habilidades: ["Detecção de segredos", "Entropia", "Precisão e revocação", "Respostas a incidentes"],
    tecnologias: ["Python ou TypeScript", "pre-commit", "Expressões regulares"],
    evidencias: ["dbir-2026", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Segredos e configuração segura", href: "/aprenda/seguranca-de-aplicacoes/segredos-e-configuracao-segura" },
    ],
    cuidado: "Use apenas segredos fictícios nos testes e nunca publique um segredo real encontrado em repositórios de terceiros: avise os donos em privado.",
  },
  {
    slug: "home-lab-de-rede-documentado",
    titulo: "Home lab de rede tratado como projeto de trabalho",
    gancho: "Monte uma rede com VLANs, roteamento, DHCP, DNS e ACLs, documente como um projeto de empresa e quebre de propósito para mostrar o diagnóstico.",
    nivel: "Intermediário",
    area: "redes",
    tempo: "3 a 4 semanas",
    problema: "Quase todo mundo termina um laboratório e não deixa nada que outra pessoa possa avaliar. Os guias de portfólio de segurança e de infraestrutura repetem o mesmo conselho: descreva o seu laboratório como descreveria um projeto de trabalho, com o que montou, por quê e o que aprendeu. É o formato que transforma estudo em evidência.",
    construir: [
      "Uma topologia com ao menos três redes (usuários, servidores e visitantes), VLANs, um roteador, DHCP, DNS e ACLs que isolam os visitantes, montada no simulador do Koda ou em uma ferramenta como containerlab ou GNS3.",
      "Um plano de endereçamento e um diagrama, atualizados com a topologia.",
      "Um script que testa uma matriz de conectividade (quem deve alcançar quem) e imprime o resultado esperado versus o real.",
      "Três falhas provocadas de propósito (rota faltando, ACL errada, DHCP esgotado) com o diagnóstico passo a passo.",
    ],
    diferencial: [
      "A matriz de conectividade no CI do repositório: se uma mudança na configuração quebrar o isolamento, o build falha.",
      "Um documento de decisões: por que cada ACL existe e o que ela impede.",
      "Os arquivos de configuração versionados, e não apenas capturas de tela.",
    ],
    entregaveis: [
      "O repositório com configurações, o plano de endereçamento e o diagrama.",
      "O script da matriz de conectividade e o relatório de testes.",
      "O diário das três falhas e dos diagnósticos.",
    ],
    comoSerVisto: [
      "Publique o diário das falhas: 'o que quebrei e como achei' é um formato que se lê e se compartilha.",
      "Mostre a matriz de conectividade como uma tabela verde e vermelha simples.",
      "Use o projeto como a seção principal do currículo para vagas de infraestrutura, nuvem e segurança.",
    ],
    sinalNaCarreira: "É exatamente o formato que os guias de portfólio de segurança recomendam: laboratório documentado como projeto de trabalho. E automatizar a verificação das regras de isolamento é uma prática de infraestrutura como código, no vocabulário que as equipes de engenharia usam.",
    habilidades: ["VLANs e roteamento", "ACLs e isolamento", "DHCP e DNS", "Diagnóstico", "Automação de testes de rede"],
    tecnologias: ["Simulador de Redes do Koda, containerlab ou GNS3", "Python ou shell", "Git"],
    evidencias: ["guias-de-seguranca", "guias-de-portfolio", "dora"],
    estudarNoKoda: [
      { rotulo: "ACLs e firewall", href: "/aprenda/redes-de-computadores/acls-e-firewall" },
      { rotulo: "DHCP e DNS", href: "/aprenda/redes-de-computadores/dhcp-e-dns" },
      { rotulo: "Laboratórios de Redes", href: "/redes" },
    ],
  },
  {
    slug: "biblioteca-de-feriados-do-brasil",
    titulo: "Biblioteca de feriados e dias úteis do Brasil, publicada de verdade",
    gancho: "Publique um pacote pequeno que resolve um problema chato e real: calcular prazos em dias úteis com feriados nacionais, estaduais e municipais.",
    nivel: "Intermediário",
    area: "open-source",
    tempo: "4 semanas",
    problema: "Prazos em dias úteis aparecem em boletos, contratos, entregas e processos, e toda empresa brasileira reescreve essa lógica, quase sempre errada para feriados móveis e municipais. Um pacote pequeno, bem testado e bem documentado resolve um problema de nicho que ninguém quer reescrever, e tem usuários reais, o que um projeto de exercício não tem.",
    construir: [
      "Funções para: verificar se uma data é dia útil, somar e subtrair dias úteis, e listar feriados por ano, estado e município.",
      "Feriados móveis calculados (Carnaval, Sexta-feira Santa, Corpus Christi a partir da Páscoa) e uma base de dados estaduais e municipais versionada, com fonte para cada entrada.",
      "Testes com casos conhecidos e testes baseados em propriedades (somar n dias úteis e subtrair n volta à data original, quando ela é útil).",
      "Publicação no registro da linguagem (npm ou PyPI) com versionamento semântico, changelog e integração contínua.",
    ],
    diferencial: [
      "Uma forma de contribuir com feriados municipais via pull request, com um modelo e validação automática dos dados.",
      "Tipos bem definidos e mensagens de erro claras.",
      "Um arquivo que documenta as decisões ambíguas (ponto facultativo, feriado que cai no domingo) e a fonte legal de cada regra.",
    ],
    entregaveis: [
      "O pacote publicado, com a versão e o changelog.",
      "O repositório com testes, CI e guia de contribuição.",
      "A documentação com exemplos de uso reais.",
    ],
    comoSerVisto: [
      "Quem tem esse problema procura no registro de pacotes: bons nome, descrição e palavras-chave são parte do projeto.",
      "Divulgue em comunidades brasileiras de desenvolvimento com um exemplo curto do problema que o pacote resolve.",
      "Quando alguém abrir uma issue ou um PR, responda bem: o histórico de manutenção é a parte que mais convence.",
    ],
    sinalNaCarreira: "Um pacote publicado mostra que você leva um projeto até o fim: nomeia, versiona, documenta, testa e mantém. O Open Source Guide lista a manutenção e a relação com a comunidade como parte do valor de código aberto. E ter usuários reais é algo que a maioria dos portfólios não consegue mostrar.",
    habilidades: ["Design de API", "Testes baseados em propriedades", "Versionamento semântico", "Manutenção de projeto"],
    tecnologias: ["TypeScript (npm) ou Python (PyPI)", "GitHub Actions", "Hypothesis ou fast-check"],
    evidencias: ["opensource-guide", "octoverse-2025", "guias-de-portfolio"],
    estudarNoKoda: [
      { rotulo: "Tipagem e qualidade em Python", href: "/aprenda/python/tipagem-e-qualidade" },
      { rotulo: "Classes, módulos e projeto em TypeScript", href: "/aprenda/typescript/classes-modulos-e-projeto" },
    ],
    cuidado: "Verifique cada feriado em fonte oficial (lei ou decreto) e registre a fonte, porque um feriado errado em um prazo jurídico tem consequências.",
  },
  {
    slug: "auditoria-de-acessibilidade-real",
    titulo: "Auditoria de acessibilidade de um serviço da sua cidade, com correção",
    gancho: "Avalie um site de serviço público ou de uma ONG com leitor de tela e teclado, escreva o relatório e, se for código aberto, envie a correção.",
    nivel: "Intermediário",
    area: "frontend",
    tempo: "3 semanas",
    problema: "Acessibilidade costuma ser citada em portfólios e raramente demonstrada. Uma auditoria real, em um serviço que pessoas de fato precisam usar, com problemas encontrados, impacto descrito e correções propostas, é rara e tem valor para quem recebe. Os critérios são públicos (WCAG), então o trabalho pode ser conferido por qualquer pessoa.",
    construir: [
      "Escolha um serviço que dependa de formulários ou de informação essencial (agendamento, consulta de benefício, inscrição) e use-o apenas com teclado e com um leitor de tela, registrando onde trava.",
      "Avalie contra critérios da WCAG: contraste, rótulos de formulário, ordem de foco, textos alternativos, mensagens de erro, tempo limite.",
      "Escreva um relatório com cada problema, o critério violado, o impacto para quem usa e a correção proposta com um trecho de código.",
      "Reproduza as três correções mais importantes em uma cópia do componente, com testes de acessibilidade automatizados.",
    ],
    diferencial: [
      "Avalie também no celular, com zoom de texto a 200% e com o modo de alto contraste.",
      "Priorize os problemas por impacto e esforço, e não só os liste.",
      "Se o projeto for código aberto, envie as correções; se não for, mande o relatório ao responsável, de forma educada e construtiva.",
    ],
    entregaveis: [
      "O relatório de auditoria, com evidências (gravações de tela ou capturas, sem dados pessoais).",
      "As correções de exemplo com testes automatizados.",
      "A resposta (ou a falta de resposta) de quem recebeu, com o resultado.",
    ],
    comoSerVisto: [
      "Se a organização corrigir, peça permissão e publique o antes e o depois: uma melhoria real, com nome, vale mais do que qualquer demonstração.",
      "Escreva o relatório de modo que uma pessoa não técnica entenda o impacto: um parágrafo sobre o que é impossível fazer com um leitor de tela é mais forte do que uma lista de critérios.",
      "Compartilhe em comunidades de acessibilidade e de front-end: o tema tem pessoas dispostas a revisar e ampliar.",
    ],
    sinalNaCarreira: "Mostra empatia, rigor técnico e comunicação com quem não é técnico, qualidades que a pesquisa da ISC2 destaca. E a acessibilidade é uma obrigação crescente em serviços digitais, o que torna a habilidade concreta em vez de apenas desejável.",
    habilidades: ["WCAG", "Leitores de tela", "HTML semântico", "Testes de acessibilidade", "Relatórios técnicos"],
    tecnologias: ["NVDA ou VoiceOver", "axe ou Lighthouse", "HTML, CSS e JavaScript"],
    evidencias: ["isc2-2024", "opensource-guide"],
    estudarNoKoda: [
      { rotulo: "Trilha de TypeScript", href: "/aprenda/typescript" },
    ],
    cuidado: "Avalie apenas o uso normal do serviço, sem tentar burlar nada, e não colete dados de ninguém. Comunique os problemas ao responsável antes de publicar detalhes.",
  },
];
