import type { IdeiaDeProjeto } from "./tipos";

export const PROJETOS_INICIANTE_E_JUNIOR: IdeiaDeProjeto[] = [
  {
    slug: "readme-que-funciona",
    titulo: "O README que ninguém testou",
    gancho: "Teste o passo a passo de instalação de três projetos que você usa, em uma máquina limpa, e corrija o que quebra.",
    nivel: "Iniciante",
    area: "open-source",
    tempo: "1 a 2 semanas",
    problema: "Quase todo projeto tem um README escrito por quem já tinha tudo instalado. O resultado é um guia que falha para a primeira pessoa de fora, e essa pessoa é você. Documentação é a contribuição que mais falta e a que mantenedores mais agradecem, e ao contrário de código novo, quase nunca é recusada por motivos técnicos.",
    construir: [
      "Escolha três projetos pequenos ou médios que você realmente usa, e que tenham guia de instalação.",
      "Para cada um, crie um contêiner ou máquina virtual limpa e siga o README à risca, sem improvisar. Anote cada comando que falhou, cada pré-requisito que faltou e o tempo até o primeiro sucesso.",
      "Abra um pull request por projeto corrigindo o que quebrou (um pré-requisito, um comando desatualizado, uma versão errada), seguindo o guia de contribuição do próprio projeto.",
      "Se o projeto não tem guia de contribuição, proponha um, curto e do tamanho do projeto.",
    ],
    diferencial: [
      "Meça e publique o tempo até o primeiro sucesso antes e depois da sua correção, como número.",
      "Automatize o teste: um script simples que roda o passo a passo em um contêiner limpo e falha quando o README para de funcionar, sugerido como verificação de CI.",
      "Escreva um texto curto sobre o método, para outras pessoas repetirem em outros projetos.",
    ],
    entregaveis: [
      "Os pull requests abertos, com link, e o resultado de cada um (aceito, em revisão, com comentários).",
      "Uma planilha ou arquivo com o diário do teste: comando, falha, causa, correção, tempo.",
      "O texto do método, publicado no seu perfil, blog ou LinkedIn.",
    ],
    comoSerVisto: [
      "Cite no texto os mantenedores que revisaram, de forma respeitosa: eles verão a menção e podem comentar.",
      "Publique o método com o título como pergunta que alguém digitaria, como 'como testar o README de um projeto de código aberto'.",
      "Fixe os pull requests aceitos no seu perfil do GitHub e liste-os no currículo como contribuições, com o nome do projeto.",
    ],
    sinalNaCarreira: "Mostra comunicação clara, atenção ao detalhe e capacidade de trabalhar com a equipe de outra pessoa, que são justamente o que a pesquisa da ISC2 aponta como prioridade para vagas de entrada. E ataca uma lacuna medida: segundo o Octoverse, só 63% dos repositórios têm README e 5,5% têm guia de contribuição.",
    habilidades: ["Escrita técnica", "Git e pull requests", "Reprodutibilidade", "Comunicação com mantenedores"],
    tecnologias: ["Git", "Docker", "Markdown", "GitHub"],
    evidencias: ["octoverse-2025", "opensource-guide", "isc2-2024"],
    estudarNoKoda: [{ rotulo: "Ferramentas do dia a dia", href: "/ferramentas" }],
    cuidado: "Leia as regras de contribuição de cada projeto antes de abrir um PR e abra uma issue primeiro se for uma mudança grande. Muitos projetos recusam PRs sem discussão prévia.",
  },
  {
    slug: "pipeline-que-voce-mede",
    titulo: "Um pipeline que mede a si mesmo",
    gancho: "Monte integração e entrega contínuas para uma aplicação pequena e publique as métricas DORA do seu próprio repositório.",
    nivel: "Iniciante",
    area: "nuvem-devops",
    tempo: "2 semanas",
    problema: "Todo portfólio diz 'usei CI/CD', e quase nenhum mostra o que isso mudou. As equipes de engenharia falam em métricas (frequência de deploy, tempo de entrega, taxa de falha, tempo de recuperação), e quem consegue medir o próprio fluxo, mesmo que pequeno, fala a mesma língua.",
    construir: [
      "Pegue uma aplicação pequena sua, com testes, e configure o pipeline: testes, verificação de estilo e build a cada push, e deploy automático a cada merge na branch principal.",
      "Adicione um script que lê o histórico do repositório e dos deploys e calcula as quatro métricas de entrega.",
      "Faça pelo menos 20 mudanças pequenas ao longo de duas a três semanas, incluindo uma que quebra de propósito, para medir falha e recuperação.",
    ],
    diferencial: [
      "Um painel simples (uma página estática gerada pelo pipeline) com as métricas ao longo do tempo.",
      "Uma regra de proteção: o deploy só acontece com testes verdes, e a reversão é um comando documentado.",
      "Um parágrafo de interpretação honesto: o que as métricas mostram e por que, em um projeto de uma pessoa só, elas significam algo diferente do que em uma equipe.",
    ],
    entregaveis: [
      "O repositório com o pipeline como código e a aplicação no ar.",
      "O painel de métricas e o script que o gera.",
      "O README com a decisão de cada etapa do pipeline e o que a quebra proposital ensinou.",
    ],
    comoSerVisto: [
      "Coloque o selo de status do pipeline e o link do painel no topo do README: é a primeira coisa que alguém vê.",
      "Escreva sobre a quebra proposital e a recuperação: histórias de falha controlada são mais lembradas do que de sucesso.",
      "Compartilhe o painel em comunidades de DevOps com uma pergunta aberta sobre como interpretar as métricas em projetos pessoais.",
    ],
    sinalNaCarreira: "A pesquisa DORA é a referência do setor em desempenho de entrega, e usar o seu vocabulário mostra que você pensa como uma equipe de engenharia. Mostra também a prática de medir antes de opinar, algo que a maioria dos projetos de iniciantes não tem.",
    habilidades: ["Integração e entrega contínuas", "Métricas de engenharia", "Automação", "Reversão segura"],
    tecnologias: ["GitHub Actions", "Docker", "Um serviço de hospedagem", "Script em Python ou TypeScript"],
    evidencias: ["dora", "guias-de-portfolio"],
    estudarNoKoda: [
      { rotulo: "Testes com pytest", href: "/aprenda/python/testes-com-pytest" },
      { rotulo: "Testes com Vitest e Supertest", href: "/aprenda/typescript/testes-com-vitest-e-supertest" },
    ],
  },
  {
    slug: "writeups-que-um-recrutador-entende",
    titulo: "Relatos de CTF que uma pessoa de fora entende",
    gancho: "Resolva cinco desafios de segurança e publique cada relato como um texto sobre raciocínio, e não como um passo a passo de respostas.",
    nivel: "Iniciante",
    area: "seguranca",
    tempo: "2 semanas",
    problema: "A internet está cheia de listas de respostas de CTF, que ninguém lê. O que quase não existe é o relato do raciocínio: o que você tentou, o que não funcionou, como percebeu o erro e como o sistema real se defenderia. Esse texto mostra, ao mesmo tempo, técnica e comunicação.",
    construir: [
      "Resolva cinco desafios da área Segurança do Koda, de categorias diferentes.",
      "Para cada um, escreva um relato com: o cenário, a primeira hipótese, o que testou e descartou, o que revelou a falha e como a falha acontece em sistemas reais.",
      "Termine cada relato com a seção 'como se defender', ligando a falha à aula da trilha correspondente.",
    ],
    diferencial: [
      "Inclua o erro: um relato que mostra uma hipótese errada e como ela foi descartada convence mais do que um caminho reto.",
      "Sem spoilers de flag: publique o raciocínio, nunca a flag, para o texto continuar útil a quem ainda vai resolver.",
      "Uma tabela final ligando cada falha a uma categoria do OWASP Top 10.",
    ],
    entregaveis: [
      "Cinco relatos publicados, de uma a duas páginas cada.",
      "Uma página índice com a tabela de falhas, defesas e links para as aulas.",
    ],
    comoSerVisto: [
      "Publique no LinkedIn e em uma plataforma de blog, e use o relato mais forte como cartão de visita no seu perfil.",
      "Escreva sempre com o mesmo formato: quem lê o primeiro relato reconhece e lê os outros.",
      "Compartilhe em comunidades de segurança perguntando se a seção de defesa está correta: a conversa gera visibilidade e correção.",
    ],
    sinalNaCarreira: "Os guias de portfólio em segurança recomendam relatos de desafios, e a pesquisa da ISC2 indica que quem contrata para entrada valoriza resolução de problemas, curiosidade e comunicação. Um relato bem escrito demonstra os três de uma vez e funciona mesmo sem experiência formal.",
    habilidades: ["Raciocínio de segurança", "Escrita técnica", "Mapeamento para OWASP", "Defesa em profundidade"],
    tecnologias: ["Área Segurança do Koda", "Markdown"],
    evidencias: ["isc2-2024", "guias-de-seguranca", "dbir-2026"],
    estudarNoKoda: [
      { rotulo: "Desafios de segurança", href: "/seguranca" },
      { rotulo: "Trilha de Segurança de aplicações", href: "/aprenda/seguranca-de-aplicacoes" },
    ],
    cuidado: "Use só ambientes feitos para treino e nunca publique segredos ou dados reais. Todos os desafios do Koda são fictícios.",
  },
  {
    slug: "um-bug-de-verdade-um-teste",
    titulo: "Um bug de verdade, um teste que o reproduz",
    gancho: "Escolha uma issue aberta em um projeto que você usa, escreva primeiro o teste que falha e só então corrija.",
    nivel: "Júnior",
    area: "open-source",
    tempo: "2 a 4 semanas",
    problema: "A maioria das 'primeiras contribuições' é mudar uma vírgula. A contribuição que quase ninguém faz, e que mantenedores adoram, é a que vem com um teste que reproduz o problema antes da correção. Ela prova que o bug existe, protege contra o retorno e facilita a revisão.",
    construir: [
      "Procure issues com rótulos como good first issue ou help wanted em projetos ativos que você usa, e confirme que o bug ainda ocorre na versão atual.",
      "Escreva um teste que falha e descreve o problema, e só depois a correção mínima que o faz passar.",
      "Abra o pull request com a descrição no formato: problema, como reproduzir, causa, solução, riscos. Responda a cada comentário da revisão.",
      "Acompanhe até o merge ou até uma recusa justificada, e registre o que aprendeu.",
    ],
    diferencial: [
      "Faça a triagem antes: reproduza outras issues do mesmo projeto e deixe comentários com passos mínimos de reprodução, o que mantenedores valorizam muito.",
      "Documente o raciocínio da causa-raiz no PR, e não só a mudança.",
      "Escreva um post-mortem curto do PR: o que achou que era a causa, o que era de fato, o que a revisão te ensinou.",
    ],
    entregaveis: [
      "O pull request, com testes, e o histórico de revisão.",
      "Os comentários de triagem em outras issues.",
      "O post-mortem do PR em texto curto.",
    ],
    comoSerVisto: [
      "Contribuições aceitas em projetos reais ficam no seu perfil do GitHub e são verificáveis por quem contrata, sem depender de você contar.",
      "Agradeça publicamente a revisão: a pessoa que mantém o projeto costuma responder e amplifica.",
      "Repita em um segundo projeto: duas contribuições aceitas em projetos distintos são um padrão, e não um acaso.",
    ],
    sinalNaCarreira: "O Open Source Guide lista exatamente isso como o valor de contribuir: exemplos públicos das suas habilidades, experiência em equipe e relacionamentos. Tudo fica registrado em um lugar que quem contrata pode abrir. É a forma mais concreta de mostrar que você trabalha dentro do código dos outros, que é como o trabalho real acontece.",
    habilidades: ["Leitura de código alheio", "Testes automatizados", "Depuração", "Revisão de código"],
    tecnologias: ["Git", "A linguagem do projeto escolhido", "Framework de testes do projeto"],
    evidencias: ["opensource-guide", "octoverse-2025", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Testes com pytest", href: "/aprenda/python/testes-com-pytest" },
      { rotulo: "Testes com Vitest e Supertest", href: "/aprenda/typescript/testes-com-vitest-e-supertest" },
    ],
    cuidado: "Respeite o ritmo dos mantenedores, que são voluntários. Se não houver resposta em algumas semanas, um lembrete educado é suficiente.",
  },
  {
    slug: "webhooks-sem-perder-nem-duplicar",
    titulo: "Receptor de webhooks que não perde nem duplica",
    gancho: "Construa um serviço que recebe eventos de outro sistema com assinatura verificada, idempotência e reprocessamento, e prove que ele aguenta falhas injetadas.",
    nivel: "Júnior",
    area: "backend",
    tempo: "3 a 4 semanas",
    problema: "Todo sistema real recebe eventos de outro (pagamentos, repositórios, entregas), e eles chegam atrasados, repetidos e fora de ordem. Um receptor ingênuo cobra duas vezes ou perde um pedido. Quase nenhum projeto de iniciante lida com isso, e é exatamente a classe de problema que as empresas enfrentam em produção.",
    construir: [
      "Um serviço que recebe webhooks, verifica a assinatura HMAC antes de qualquer processamento e responde rápido, deixando o trabalho para uma fila.",
      "Idempotência: o mesmo evento entregue duas vezes tem o mesmo efeito de uma entrega, usando o identificador do evento.",
      "Reprocessamento com recuo exponencial e uma fila de eventos mortos para o que falha repetidamente, com uma rota para inspecionar e reenviar.",
      "Um gerador de eventos de teste que injeta duplicatas, atrasos, ordem trocada e falhas do seu próprio código.",
    ],
    diferencial: [
      "Testes que provam as garantias, e não só o caminho feliz: 'mil eventos com 30% de duplicatas resultam em exatamente mil efeitos'.",
      "Tratamento de ordem: um evento de cancelamento que chega antes do de criação não pode corromper o estado.",
      "Métricas simples (eventos recebidos, duplicados, em reprocessamento, mortos) em uma página.",
    ],
    entregaveis: [
      "O repositório com testes de falha e o gerador de eventos.",
      "Um diagrama de sequência do caminho de um evento, incluindo as falhas.",
      "Um texto com as garantias que o serviço dá e as que ele não dá (ao menos uma vez, no máximo uma vez, e como se chega ao efeito único).",
    ],
    comoSerVisto: [
      "Publique o texto das garantias: é um tema que engenheiros experientes discutem, e é raro vê-lo bem explicado por alguém de nível júnior.",
      "Grave um vídeo curto rodando o gerador de eventos e mostrando o painel de métricas absorvendo o caos.",
      "Inclua o projeto como estudo de caso com os números ('1.000 eventos, 300 duplicatas, zero efeitos duplicados').",
    ],
    sinalNaCarreira: "Mostra que você pensa em falhas e em garantias, e não só em fluxos felizes, o que é a diferença entre código de tutorial e código de produção. Também mostra segurança aplicada: a verificação de assinatura é uma das primeiras defesas em integrações reais.",
    habilidades: ["Confiabilidade", "Idempotência", "Filas e reprocessamento", "Assinatura HMAC", "Testes de falha"],
    tecnologias: ["Python/FastAPI ou TypeScript/Express", "PostgreSQL", "Uma fila (ou tabela de fila)"],
    evidencias: ["isc2-2024", "dora"],
    estudarNoKoda: [
      { rotulo: "API com FastAPI e Pydantic", href: "/aprenda/python/api-com-fastapi-e-pydantic" },
      { rotulo: "Criptografia aplicada (HMAC)", href: "/aprenda/seguranca-de-aplicacoes/criptografia-aplicada" },
    ],
  },
  {
    slug: "dados-publicos-uma-pergunta",
    titulo: "Dados públicos do Brasil, uma pergunta de verdade",
    gancho: "Escolha uma pergunta que a sua cidade ou setor poderia ter respondida por dados abertos e entregue uma análise reproduzível, com limites declarados.",
    nivel: "Júnior",
    area: "dados-ia",
    tempo: "3 a 4 semanas",
    problema: "Painéis genéricos com dados de COVID ou de filmes são o portfólio mais repetido da área de dados. O que se destaca é uma pergunta específica, com fonte pública brasileira, tratamento honesto dos dados sujos e conclusões que reconhecem seus limites. Isso se parece muito mais com o trabalho de análise real, e também pode interessar a jornalistas e organizações locais.",
    construir: [
      "Defina uma pergunta concreta e que alguém tenha interesse em responder (por exemplo, sobre transporte, saúde, educação ou gastos da sua cidade) e justifique por que ela importa.",
      "Reúna os dados de fontes abertas como dados.gov.br, Base dos Dados, IBGE ou portais de transparência, documentando de onde veio cada tabela e quando foi baixada.",
      "Construa um pipeline reproduzível: baixar, limpar, validar, analisar, com um comando que refaz tudo do zero.",
      "Escreva testes de qualidade dos dados (valores impossíveis, duplicatas, mudanças de formato entre anos) e registre o que foi descartado e por quê.",
    ],
    diferencial: [
      "Uma seção 'o que esta análise não prova', com as limitações e possíveis vieses, em linguagem simples.",
      "Versione os dados e o código, de modo que outra pessoa chegue ao mesmo resultado.",
      "Entregue o resultado em dois formatos: um texto para pessoas não técnicas e o repositório para as técnicas.",
    ],
    entregaveis: [
      "O repositório com o pipeline, os testes de qualidade e o passo a passo para reproduzir.",
      "O relatório (notebook ou página) com a pergunta, o método, os resultados e os limites.",
      "Uma visualização principal bem explicada, que se entenda sozinha.",
    ],
    comoSerVisto: [
      "Mande o resultado para uma organização, coletivo ou jornalista de dados ligado ao tema: um agradecimento ou uma citação vale mais que cem curtidas.",
      "Publique o texto para pessoas não técnicas onde a comunidade local lê, e o repositório para a técnica.",
      "Mantenha o projeto vivo: atualize quando saírem dados novos e registre a mudança, mostrando constância.",
    ],
    sinalNaCarreira: "Mostra que você sabe transformar uma pergunta em um método e comunicar limitações, e a pesquisa da ISC2 coloca resolução de problemas e comunicação no topo do que quem contrata procura em iniciantes. O recorte brasileiro dialoga com o mercado local, onde a Brasscom estima um déficit contínuo de profissionais de tecnologia.",
    habilidades: ["Análise de dados", "Qualidade de dados", "Reprodutibilidade", "Comunicação de resultados"],
    tecnologias: ["Python (pandas ou polars)", "SQL", "Jupyter ou Quarto", "Base dos Dados / dados.gov.br"],
    evidencias: ["brasscom", "isc2-2024", "guias-de-portfolio"],
    estudarNoKoda: [
      { rotulo: "Fundamentos da linguagem Python", href: "/aprenda/python/fundamentos-da-linguagem" },
      { rotulo: "Banco de dados com SQLAlchemy", href: "/aprenda/python/banco-de-dados-com-sqlalchemy" },
    ],
    cuidado: "Respeite a LGPD: use apenas dados abertos e anonimizados, e nunca tente reidentificar pessoas.",
  },
  {
    slug: "auditor-de-dependencias",
    titulo: "Auditor de dependências para repositórios pequenos",
    gancho: "Construa uma ferramenta que lê o arquivo de travamento de um projeto, consulta a base de vulnerabilidades e abre um relatório com plano de ação.",
    nivel: "Júnior",
    area: "seguranca",
    tempo: "3 semanas",
    problema: "Segundo o relatório DBIR 2026 da Verizon, 31% das violações começam por vulnerabilidades de software, mais do que por senhas roubadas, e boa parte vem de dependências que ninguém atualiza. As ferramentas prontas existem, mas montar uma, com as suas regras, ensina como a cadeia de suprimentos de software funciona, e entrega algo que equipes de verdade usam.",
    construir: [
      "Um programa que lê o arquivo de travamento (package-lock, poetry.lock, requirements com versões fixas) e lista todas as dependências, diretas e transitivas.",
      "Consulta à base aberta OSV para cada dependência e versão, e classificação por severidade.",
      "Um relatório em Markdown com o que está vulnerável, a versão corrigida mais próxima e o risco de atualizar (mudança de versão maior).",
      "Uma execução em CI que falha em severidade alta e comenta no pull request.",
    ],
    diferencial: [
      "Detecção de typosquatting: sinalizar pacotes com nome parecido ao de pacotes populares.",
      "Geração de um inventário (SBOM) do projeto, em formato padrão.",
      "Rode a ferramenta em vinte repositórios públicos pequenos e publique os dados agregados, sem expor ninguém, como um estudo de caso de higiene de dependências.",
    ],
    entregaveis: [
      "O repositório com testes (inclusive com dependências falsas vulneráveis) e a ação de CI pronta para uso.",
      "Um exemplo de relatório gerado.",
      "O texto do estudo de caso com os números agregados.",
    ],
    comoSerVisto: [
      "Publique a ação como algo que outros possam usar com uma linha, com documentação enxuta e um selo.",
      "O estudo agregado é um tipo de conteúdo que circula: títulos com número concreto, como '20 projetos, 14 com dependências vulneráveis'.",
      "Avise os mantenedores dos problemas encontrados, em privado e com cuidado, antes de publicar qualquer detalhe.",
    ],
    sinalNaCarreira: "Mostra segurança aplicada a algo que a indústria mede: o DBIR coloca vulnerabilidades de software como a principal porta de entrada hoje. Mostra também que você entende a cadeia de suprimentos, e a ISC2 lista segurança de aplicações e de nuvem entre as maiores lacunas de habilidades das equipes.",
    habilidades: ["Segurança de dependências", "Análise de lockfiles", "Integração com CI", "Divulgação responsável"],
    tecnologias: ["Python ou TypeScript", "API do OSV", "GitHub Actions", "CycloneDX ou SPDX"],
    evidencias: ["dbir-2026", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Dependências e cadeia de suprimentos", href: "/aprenda/seguranca-de-aplicacoes/dependencias-e-cadeia-de-suprimentos" },
    ],
    cuidado: "Divulgação responsável: nunca publique uma vulnerabilidade que ainda não foi corrigida em um projeto específico. Agregue os dados e avise os mantenedores antes.",
  },
  {
    slug: "plano-de-enderecamento-vlsm",
    titulo: "Plano de endereçamento de uma empresa em crescimento",
    gancho: "Projete a rede de uma empresa fictícia com cinco departamentos, VLSM e margem de crescimento, e escreva uma ferramenta que valida o plano.",
    nivel: "Júnior",
    area: "redes",
    tempo: "2 a 3 semanas",
    problema: "Quase todo exercício de sub-redes termina na resposta, e o trabalho real é decidir: quantos endereços cada departamento precisa daqui a três anos, como evitar sobreposição, como deixar espaço para crescer sem renumerar. O projeto vale pela justificativa tanto quanto pela conta.",
    construir: [
      "Uma empresa fictícia com pelo menos cinco áreas (usuários, servidores, visitantes, impressoras e gestão, por exemplo), com número de dispositivos hoje e previsão de crescimento em três anos.",
      "Um plano de endereçamento com VLSM a partir de um bloco privado, com VLAN, rede, máscara, faixa, gateway e justificativa de tamanho para cada área.",
      "Um programa que lê o plano (um CSV) e valida: sobreposições, endereços fora do bloco, gateway fora da rede, sub-redes pequenas demais para a previsão.",
      "A topologia montada no simulador de Redes do Koda, com os endereços do plano, e os testes de conectividade que provam o isolamento.",
    ],
    diferencial: [
      "Uma tabela de crescimento: quando cada sub-rede se esgota, e a estratégia para quando acontecer.",
      "Um modo do validador que sugere o próximo bloco livre.",
      "Uma comparação honesta: o que mudaria se a empresa usasse IPv6.",
    ],
    entregaveis: [
      "O plano em planilha e em CSV.",
      "O validador, com testes que incluem planos errados de propósito.",
      "O diagrama da topologia e o relatório de testes de conectividade.",
    ],
    comoSerVisto: [
      "Publique o plano como um estudo de caso, com o raciocínio de cada decisão: é um tema pouco coberto em português.",
      "Ofereça o validador como ferramenta pública, com uma página que cola o CSV e mostra os erros.",
      "Compartilhe em comunidades de redes e infraestrutura pedindo crítica ao plano: a revisão de gente experiente vira conteúdo.",
    ],
    sinalNaCarreira: "Redes é a base de nuvem, segurança e DevOps, e quem sabe planejar endereçamento entende a infraestrutura por baixo das aplicações. Em nuvem, o desenho de VPCs e sub-redes é o mesmo problema, e o mercado brasileiro tem a nuvem entre as maiores demandas, segundo a Brasscom.",
    habilidades: ["VLSM e sub-redes", "Planejamento de capacidade", "Validação automatizada", "Documentação de redes"],
    tecnologias: ["Simulador de Redes do Koda", "Python ou TypeScript", "Planilhas"],
    evidencias: ["brasscom", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Endereços IP, máscaras e o primeiro ping", href: "/aprenda/redes-de-computadores/enderecos-ip-mascaras-e-ping" },
      { rotulo: "Calculadora de sub-redes", href: "/ferramentas" },
      { rotulo: "Laboratórios de Redes", href: "/redes" },
    ],
  },
  {
    slug: "ferramenta-para-cliente-real",
    titulo: "Uma ferramenta para uma pessoa ou negócio real",
    gancho: "Resolva um problema concreto de uma ONG, associação ou pequeno negócio perto de você, com escopo combinado e um depoimento no final.",
    nivel: "Júnior",
    area: "backend",
    tempo: "4 a 6 semanas",
    problema: "O que falta na maioria dos portfólios é um usuário real. Um projeto com cliente de verdade, mesmo pequeno, tem requisitos mal explicados, prazos, mudanças de ideia e a necessidade de entregar algo que alguém use. É o que mais se parece com trabalho, e vem junto com o que nenhum tutorial ensina: conversar, priorizar e dizer não.",
    construir: [
      "Encontre uma organização pequena com uma dor concreta que software resolve (agenda de voluntários, controle de estoque, cadastro de beneficiários, orçamentos), e converse com quem usa, e não só com quem manda.",
      "Escreva uma página de escopo com o problema, o que entra e o que não entra, e como saber que deu certo. Combine por escrito.",
      "Entregue em ciclos curtos, com demonstração a cada semana e um registro de decisões.",
      "Entregue com documentação para quem não programa e um plano de manutenção: quem corrige se quebrar quando você sair.",
    ],
    diferencial: [
      "Meça o antes e o depois com um número simples (tempo para uma tarefa, erros por mês).",
      "Um depoimento escrito de quem usa, com permissão para citar.",
      "Cuidado com dados pessoais desde o início: coleta mínima, acesso restrito, cópias de segurança.",
    ],
    entregaveis: [
      "O sistema funcionando e usado, mesmo que por poucas pessoas.",
      "A página de escopo, o registro de decisões e o manual de uso.",
      "O depoimento e a medição do antes e do depois.",
    ],
    comoSerVisto: [
      "Conte a história do projeto e não só a tecnologia: o problema, a dificuldade de entender o que era preciso, o que mudou no caminho.",
      "Peça à organização para divulgar o resultado: ela tem público e interesse em agradecer.",
      "Use o depoimento e o número do antes e depois no currículo, no lugar de uma lista de tecnologias.",
    ],
    sinalNaCarreira: "Cobre o que a pesquisa da ISC2 destaca como prioridade em iniciantes (trabalho em equipe, comunicação e resolução de problemas) e responde à objeção mais comum a candidatos sem experiência: 'nunca trabalhou com um usuário de verdade'.",
    habilidades: ["Levantamento de requisitos", "Priorização", "Comunicação com não técnicos", "Entrega e manutenção"],
    tecnologias: ["A que o problema pedir: simples e que você consiga manter"],
    evidencias: ["isc2-2024", "guias-de-portfolio"],
    estudarNoKoda: [
      { rotulo: "Trilha de TypeScript", href: "/aprenda/typescript" },
      { rotulo: "Trilha de Python", href: "/aprenda/python" },
    ],
    cuidado: "Combine por escrito que o trabalho é voluntário ou remunerado, e quem é dono do código. Respeite a LGPD ao guardar dados de pessoas.",
  },
];
