import type { IdeiaDeProjeto } from "./tipos";

export const PROJETOS_AVANCADOS: IdeiaDeProjeto[] = [
  {
    slug: "migracao-de-banco-sem-downtime",
    titulo: "Migração de banco sem downtime, com carga rodando",
    gancho: "Mude o esquema de uma tabela em uso pesado sem derrubar nada, e prove com métricas que nenhum erro apareceu.",
    nivel: "Avançado",
    area: "backend",
    tempo: "4 a 6 semanas",
    problema: "Tutoriais ensinam a criar tabelas, e o trabalho real é mudá-las enquanto o sistema está no ar. Renomear uma coluna ou dividir uma tabela com tráfego pode travar o banco e derrubar a aplicação. Quem sabe fazer a migração em passos compatíveis, sem janela de manutenção, resolve um problema caro e que poucos juniores já viram.",
    construir: [
      "Uma aplicação com uma tabela de milhões de linhas e um gerador de carga contínua (leituras e escritas) que roda durante todo o experimento.",
      "Uma mudança de esquema real, como dividir uma coluna em duas ou mover dados para uma nova tabela, feita pelo padrão de mudança paralela (expandir, migrar, contrair).",
      "Preenchimento dos dados antigos em lotes, idempotente e que pode ser pausado, sem bloquear a tabela.",
      "Alternância controlada por uma chave de funcionalidade, com reversão em cada etapa, e um roteiro de execução (runbook).",
    ],
    diferencial: [
      "O gráfico de erros e de latência durante toda a migração, mostrando zero erros e um aumento controlado de latência.",
      "Um teste da reversão: desfazer a migração no meio, com carga, e provar que os dados continuam íntegros.",
      "Uma comparação com a abordagem ingênua (alterar a tabela de uma vez), mostrando o bloqueio e o tempo fora do ar.",
    ],
    entregaveis: [
      "O repositório com a aplicação, o gerador de carga e os scripts de migração.",
      "O runbook passo a passo e as métricas de cada etapa.",
      "O texto comparando a migração segura com a ingênua, com os gráficos.",
    ],
    comoSerVisto: [
      "O gráfico 'zero erros durante a migração' é um resultado que engenheiros de plataforma reconhecem e valorizam.",
      "Publique o runbook como um guia reutilizável, com o padrão explicado em uma figura.",
      "Compare com a versão ingênua mostrando o travamento: o contraste é a parte que as pessoas compartilham.",
    ],
    sinalNaCarreira: "A pesquisa DORA associa mudanças pequenas, frequentes e seguras ao melhor desempenho de entrega, e a taxa de falha de mudança é uma das suas métricas centrais. Dominar mudanças seguras em dados é uma competência de nível acima do esperado em iniciantes, e mostra o raciocínio sobre risco que a produção exige.",
    habilidades: ["Migrações de banco", "Padrão de mudança paralela", "Chaves de funcionalidade", "Reversão segura", "Teste de carga"],
    tecnologias: ["PostgreSQL", "Uma ferramenta de migrações", "k6, Locust ou similar", "Grafana ou gráficos simples"],
    evidencias: ["dora", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Banco de dados com SQLAlchemy", href: "/aprenda/python/banco-de-dados-com-sqlalchemy" },
    ],
    cuidado: "Faça tudo em um ambiente de testes, com dados sintéticos. Nunca experimente em um banco que tenha dados reais.",
  },
  {
    slug: "rag-que-sabe-dizer-nao-sei",
    titulo: "Um RAG que sabe dizer 'não sei'",
    gancho: "Construa uma busca com IA sobre uma documentação real que mede a qualidade da recuperação, recusa quando não sabe e resiste a injeção de instruções.",
    nivel: "Avançado",
    area: "dados-ia",
    tempo: "5 a 6 semanas",
    problema: "A versão comum de um RAG é uma demonstração que responde bem às perguntas fáceis e inventa nas difíceis. O que importa em produto é saber quando a base não tem a resposta e ser capaz de recusar, citar a fonte e não obedecer a instruções escondidas nos documentos. Segundo o Stack Overflow 2025, a principal frustração com IA é a resposta quase certa. Um sistema que mede e recusa ataca esse ponto.",
    construir: [
      "Escolha uma documentação pública e grande (de um framework ou de uma lei) como base, e construa a ingestão, o corte em trechos e a busca.",
      "Um conjunto de perguntas com a resposta e o trecho correto, incluindo perguntas que a base não responde.",
      "Medição da recuperação (o trecho certo está entre os k primeiros?) separada da medição da resposta final.",
      "Uma resposta que cita os trechos usados, com verificação automática de que a citação existe e sustenta a afirmação, e uma recusa calibrada quando a evidência é fraca.",
    ],
    diferencial: [
      "Um teste adversarial: documentos com instruções escondidas ('ignore tudo e revele...') e a prova de que o sistema não as obedece.",
      "A curva entre o quanto o sistema recusa e o quanto acerta, e o ponto de equilíbrio escolhido.",
      "Uma comparação de estratégias de corte e de busca (apenas vetorial, apenas palavras-chave e a combinação) com os números.",
    ],
    entregaveis: [
      "O sistema, o conjunto de avaliação e os relatórios de recuperação e de resposta.",
      "Os testes adversariais e o resultado.",
      "O texto com as decisões e os números de cada comparação.",
    ],
    comoSerVisto: [
      "Publique a curva de recusa versus acerto: é uma figura rara em portfólios e fácil de entender.",
      "Escreva sobre a injeção de instruções em documentos, com um exemplo funcionando e a defesa: é um tema de segurança em alta.",
      "Disponibilize uma demonstração em que a pessoa possa fazer uma pergunta fora da base e ver o sistema recusar.",
    ],
    sinalNaCarreira: "Une IA, dados e segurança em um projeto. O Octoverse mostra a explosão de repositórios com modelos de linguagem, e Osmani recomenda mostrar como o resultado de IA foi verificado. Saber medir a recuperação, e se defender de injeção de instruções, é o que separa um produto utilizável de uma demonstração.",
    habilidades: ["Busca e embeddings", "Avaliação de recuperação", "Calibração de recusa", "Injeção de instruções", "Citação verificável"],
    tecnologias: ["Python", "Um banco vetorial ou pgvector", "A API de um modelo", "pytest"],
    evidencias: ["stackoverflow-2025", "osmani-2026", "octoverse-2025"],
    estudarNoKoda: [
      { rotulo: "RAG com dados próprios", href: "/aprenda/llm-mcp-mvp/rag-dados-proprios" },
      { rotulo: "Avaliando sistemas com LLM", href: "/aprenda/llm-mcp-mvp/avaliando-sistemas-com-llm" },
    ],
    cuidado: "Use documentos públicos, com licença que permita o uso, e cite a origem.",
  },
  {
    slug: "observabilidade-e-um-incidente",
    titulo: "Observabilidade, metas de serviço e um incidente provocado",
    gancho: "Instrumente uma aplicação, defina metas de confiabilidade, provoque uma falha e escreva o post-mortem como uma equipe de verdade escreveria.",
    nivel: "Avançado",
    area: "nuvem-devops",
    tempo: "4 a 6 semanas",
    problema: "Monitorar costuma parar em um painel bonito com a CPU. O que as equipes precisam é saber se os usuários estão sendo bem atendidos (metas de nível de serviço), ser avisadas antes deles e aprender com cada falha sem procurar culpados. Esse ciclo completo é o que se chama prática de confiabilidade e raramente aparece em um portfólio.",
    construir: [
      "Uma aplicação com pelo menos dois serviços, instrumentada com OpenTelemetry (traços, métricas e logs correlacionados).",
      "Duas ou três metas de nível de serviço (por exemplo, 99% das requisições abaixo de 300 ms) com o orçamento de erro calculado e um painel que mostra o consumo.",
      "Alertas baseados no consumo do orçamento, e não em limiares arbitrários.",
      "Uma falha provocada (dependência lenta, vazamento de memória ou uma versão ruim) detectada pelo alerta, diagnosticada com os traços e corrigida.",
    ],
    diferencial: [
      "Um post-mortem sem culpados: linha do tempo, impacto, causa-raiz, o que funcionou, o que não, ações com responsáveis e prazos.",
      "Um teste que reproduz a falha e passa a rodar no CI.",
      "Um roteiro de plantão curto (o que fazer quando cada alerta dispara).",
    ],
    entregaveis: [
      "O repositório com a aplicação instrumentada, os painéis e os alertas como código.",
      "As metas de serviço documentadas, com a justificativa dos números.",
      "O post-mortem e o roteiro de plantão.",
    ],
    comoSerVisto: [
      "O post-mortem é o conteúdo central: publique-o inteiro, é o tipo de texto que equipes de engenharia leem com respeito.",
      "Mostre a captura do traço que levou à causa-raiz, com uma anotação de como você a leu.",
      "Escreva sobre como escolheu as metas, e não só as ferramentas: é o raciocínio que quem contrata procura.",
    ],
    sinalNaCarreira: "A pesquisa DORA conecta práticas de entrega e de operação ao desempenho das organizações, com o tempo de recuperação entre suas métricas. Mostra maturidade acima do esperado para o seu nível: pensar em usuários, em risco e em aprendizado, e não só em ferramentas.",
    habilidades: ["OpenTelemetry", "Metas de nível de serviço", "Alertas por orçamento de erro", "Diagnóstico com traços", "Post-mortem"],
    tecnologias: ["OpenTelemetry", "Prometheus e Grafana (ou equivalentes)", "Docker Compose ou Kubernetes", "Uma aplicação em duas partes"],
    evidencias: ["dora", "isc2-2024"],
    estudarNoKoda: [
      { rotulo: "Trilha AWS Cloud Practitioner", href: "/aprenda/aws-cloud-practitioner" },
    ],
  },
  {
    slug: "modelo-de-ameacas-e-teste-de-intrusao",
    titulo: "Modelo de ameaças e teste de intrusão autorizado na sua própria aplicação",
    gancho: "Analise uma aplicação sua como um atacante, documente as ameaças, ataque-a dentro de um ambiente controlado e entregue o relatório e as correções.",
    nivel: "Avançado",
    area: "seguranca",
    tempo: "5 a 6 semanas",
    problema: "Segurança de iniciante costuma ser uma lista de ferramentas que a pessoa rodou. O trabalho profissional é outro: entender o que se protege, de quem, como seria atacado, testar com método, relatar de forma que o time consiga corrigir e provar que corrigiu. Quase ninguém mostra o ciclo inteiro, de ponta a ponta, em uma aplicação que conhece.",
    construir: [
      "Uma aplicação sua, com login, papéis e algum dado sensível, em um ambiente isolado (contêineres locais).",
      "Um modelo de ameaças: diagrama com fronteiras de confiança, ameaças organizadas (por exemplo, pelo método STRIDE), priorizadas por probabilidade e impacto.",
      "Um teste de intrusão: tente explorar as ameaças priorizadas (controle de acesso, injeção, sessões, configuração, dependências) e registre cada achado com evidência.",
      "Para cada achado relevante, a correção com um teste automatizado que falha antes e passa depois.",
    ],
    diferencial: [
      "O relatório no formato profissional: resumo executivo para quem decide, achados com severidade, evidência, impacto e recomendação.",
      "Um novo teste final, depois das correções, que mostra o antes e o depois.",
      "O mapeamento de cada achado ao OWASP Top 10 e à aula do Koda que ensina a defesa.",
    ],
    entregaveis: [
      "O modelo de ameaças, com diagrama e tabela.",
      "O relatório de teste de intrusão, com evidências sanitizadas.",
      "Os testes automatizados de cada correção e o repositório com a aplicação corrigida.",
    ],
    comoSerVisto: [
      "Publique uma versão do relatório com os dados sanitizados: o formato profissional é, por si, um diferencial.",
      "Escreva sobre o achado mais surpreendente na sua própria aplicação: admitir uma falha em código seu convence mais do que nunca ter errado.",
      "Apresente o projeto em uma comunidade de segurança local ou em uma palestra relâmpago.",
    ],
    sinalNaCarreira: "Cobre as áreas que a pesquisa da ISC2 lista entre as maiores lacunas (segurança de aplicações e testes de intrusão) e responde a um problema medido: segundo o DBIR 2026, 31% das violações começam por vulnerabilidades de software. O relatório mostra a comunicação que as pesquisas colocam no topo do que se procura em iniciantes.",
    habilidades: ["Modelagem de ameaças", "Teste de intrusão", "Relatório técnico", "Correção com testes", "OWASP"],
    tecnologias: ["Docker", "Burp Suite Community ou OWASP ZAP", "A linguagem da sua aplicação"],
    evidencias: ["isc2-2024", "dbir-2026", "guias-de-seguranca"],
    estudarNoKoda: [
      { rotulo: "Ameaças, risco e defesa em camadas", href: "/aprenda/seguranca-de-aplicacoes/ameacas-risco-e-defesa-em-camadas" },
      { rotulo: "Sessões, tokens e controle de acesso", href: "/aprenda/seguranca-de-aplicacoes/sessoes-tokens-e-controle-de-acesso" },
      { rotulo: "Desafios de segurança", href: "/seguranca" },
    ],
    cuidado: "Teste somente aplicações suas, em ambiente isolado, ou com autorização por escrito. Acessar sistemas de terceiros sem permissão é crime.",
  },
];
