spring:
  application:
    name: koda
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/koda
    username: koda
    password: kodaadmin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user

server:
  servlet:
    session:
      cookie:
        name: KODA_SESSAO

koda:
  seguranca:
    chave-criptografia: ${TOKEN_ENCRYPTION_KEY}
  github:
    api-url: https://api.github.com
  frontend:
      url: http://localhost:3000