import type { Aula } from "./tipos";

export const AULA_SEGREDOS: Aula = {
  slug: "segredos-dependencias-logs-e-configuracao-segura",
  titulo: "Segredos, dependências, logs e configuração segura",
  resumo: "O que nunca vai para o repositório, como confiar (e desconfiar) de bibliotecas de terceiros e o que registrar, e o que jamais registrar.",
  trilha: "seguranca",
  nivel: "Intermediário",
  leitura: "22 min",
  preRequisitos: [
    "Usar Git e ter enviado código para um repositório remoto.",
    "Ter instalado dependências com npm, pip ou Maven.",
  ],
  pontosChave: [
    "Um segredo que entrou em um commit deve ser tratado como vazado, mesmo depois de apagado: o histórico guarda tudo.",
    "Segredos vivem em variáveis de ambiente ou em um gerenciador de segredos, nunca no código nem em imagens.",
    "A maior parte do seu código é de terceiros: mantenha um inventário e atualize com rotina.",
    "Logs devem ajudar quem investiga sem entregar segredos nem dados pessoais.",
    "Configuração de produção é diferente da de desenvolvimento, e o padrão seguro é o que vem desligado de depuração.",
  ],
  blocos: [
    { tipo: "p", texto: "Muitos incidentes de segurança não envolvem nenhuma técnica sofisticada: uma chave de API esquecida em um repositório público, uma biblioteca antiga com falha conhecida, um log que guardou a senha de todo mundo, o modo de depuração ligado em produção. Este artigo cobre esse conjunto de cuidados do dia a dia." },

    { tipo: "h", texto: "Segredos: o que são e onde moram" },
    { tipo: "p", texto: "Segredo é tudo o que dá acesso ou prova identidade e não pode ser público: senhas de banco, chaves de API, tokens de acesso, chaves privadas, chaves de assinatura de JWT, segredos de clientes OAuth, certificados." },
    { tipo: "h3", texto: "Nunca no código, nunca no Git" },
    { tipo: "alerta", titulo: "O Git não esquece", texto: "Se um segredo foi para um commit, ele está no histórico do repositório, mesmo que você o apague no commit seguinte. Qualquer pessoa que clone o repositório pode recuperá-lo. Em repositórios públicos, robôs varrem o GitHub o tempo todo atrás de chaves, e elas costumam ser usadas em minutos. A regra, portanto, é: segredo que vazou está comprometido e deve ser revogado e trocado, não apenas apagado." },
    { tipo: "p", texto: "Então, o que fazer quando acontece? Em ordem:" },
    { tipo: "numerada", itens: [
      "Revogar ou rotacionar o segredo imediatamente no serviço de origem (gerar uma nova chave e desativar a antiga).",
      "Verificar nos registros do serviço se a chave antiga foi usada por alguém.",
      "Só depois, se quiser, limpar o histórico com ferramentas como git filter-repo. Isso é higiene, não substitui a rotação.",
      "Descobrir por que aconteceu e colocar uma proteção (veja a seção de detecção).",
    ] },
    { tipo: "h3", texto: "Variáveis de ambiente e arquivo .env" },
    { tipo: "p", texto: "O padrão mais comum é ler os segredos do ambiente em que o programa roda, em vez de escrevê-los no código. Em desenvolvimento, um arquivo .env guarda esses valores na máquina de cada pessoa, e o .gitignore garante que ele nunca seja versionado." },
    { tipo: "codigo", linguagem: "bash", legenda: ".gitignore", texto: "# Segredos locais\n.env\n.env.local\n*.pem\n*.key" },
    { tipo: "codigo", linguagem: "bash", legenda: ".env.example (este sim vai para o Git, sem valores reais)", texto: "DATABASE_URL=\nJWT_SECRET=\nPAYMENT_API_KEY=\nSMTP_PASSWORD=" },
    { tipo: "p", texto: "O arquivo .env.example documenta quais variáveis o projeto precisa, sem expor nenhum valor. Quem entra no time copia para .env e preenche." },
    { tipo: "codigo", linguagem: "typescript", legenda: "Ler e exigir a variável na inicialização", texto: "function exigir(nome: string): string {\n  const valor = process.env[nome];\n  if (!valor) {\n    // Falhar cedo, com o nome da variável, nunca com o valor\n    throw new Error(`Variável de ambiente ausente: ${nome}`);\n  }\n  return valor;\n}\n\nexport const configuracao = {\n  banco: exigir(\"DATABASE_URL\"),\n  segredoDoJwt: exigir(\"JWT_SECRET\"),\n};" },
    { tipo: "codigo", linguagem: "python", legenda: "Python com pydantic-settings", texto: "from pydantic_settings import BaseSettings\n\n\nclass Configuracao(BaseSettings):\n    database_url: str\n    jwt_secret: str\n\n    model_config = {\"env_file\": \".env\"}\n\n\nconfiguracao = Configuracao()  # falha na partida se faltar algo" },
    { tipo: "codigo", linguagem: "java", legenda: "Spring: a propriedade lê da variável", texto: "# application.yml\nspring:\n  datasource:\n    url: ${DATABASE_URL}\n    password: ${DATABASE_PASSWORD}\n\n# Nenhum valor real no arquivo: ele vai para o Git." },
    { tipo: "h3", texto: "Variáveis de ambiente bastam?" },
    { tipo: "p", texto: "Para projetos pequenos, sim, desde que o ambiente de produção as injete de forma segura. Em ambientes maiores, usa-se um gerenciador de segredos, como o HashiCorp Vault, o AWS Secrets Manager, o Google Secret Manager ou o Azure Key Vault. Eles trazem controle de quem lê cada segredo, registro de acessos, rotação automática e versões." },
    { tipo: "lista", itens: [
      "Um segredo diferente por ambiente (desenvolvimento, teste, produção). Um vazamento em teste não pode comprometer a produção.",
      "Privilégio mínimo: a chave de API deve ter só as permissões que o sistema usa.",
      "Rotação periódica e rotação imediata em caso de suspeita.",
      "Segredos em imagens Docker e em arquivos de configuração versionados contam como vazamento. Inclua-os apenas em tempo de execução.",
    ] },
    { tipo: "h3", texto: "Como detectar segredos esquecidos" },
    { tipo: "lista", itens: [
      "gitleaks e trufflehog: varrem o repositório e o histórico procurando padrões de chaves.",
      "GitHub secret scanning e push protection: avisam, e podem até bloquear o envio de um commit que contenha um segredo conhecido.",
      "Um hook de pré-commit que roda uma dessas ferramentas antes de o commit ser criado, que é o momento mais barato de evitar o problema.",
    ] },

    { tipo: "h", texto: "Segredos em contêineres e na integração contínua" },
    { tipo: "p", texto: "Dois lugares onde segredos escapam com frequência são as imagens Docker e os pipelines de integração contínua (CI)." },
    { tipo: "h3", texto: "Imagens Docker" },
    { tipo: "p", texto: "Uma imagem é feita de camadas, e cada instrução do Dockerfile cria uma. Se você copia um arquivo com segredo (COPY .env .) ou define uma senha com ENV ou ARG, ela fica gravada nas camadas, e quem tiver acesso à imagem consegue lê-la com docker history ou extraindo as camadas, mesmo que uma instrução posterior apague o arquivo." },
    { tipo: "lista", itens: [
      "Não coloque segredos na imagem. Injete-os na execução, por variáveis de ambiente ou por arquivos montados (secrets do Docker, do Compose ou do Kubernetes).",
      "Se um passo da construção precisa de um segredo (como um token para baixar um pacote privado), use os segredos de build do BuildKit (--mount=type=secret), que não ficam registrados nas camadas.",
      "Adicione o .env e as chaves ao .dockerignore, para que um COPY descuidado não os leve para a imagem.",
      "No Kubernetes, lembre que um objeto Secret é apenas codificado em base64: o que o protege são as permissões de acesso e a criptografia em repouso configurada no cluster.",
    ] },
    { tipo: "h3", texto: "Pipelines de CI/CD" },
    { tipo: "lista", itens: [
      "Guarde os segredos no cofre da própria plataforma (os secrets do GitHub Actions, por exemplo), e não no arquivo do pipeline. Eles ficam criptografados e são mascarados nos logs.",
      "Não os imprima: um echo de uma variável com segredo, ou um modo de depuração que despeje o ambiente, pode expô-los, e o mascaramento não cobre versões transformadas do valor.",
      "Em pipelines acionados por pull requests de repositórios de terceiros (forks), os segredos normalmente não são entregues. Não contorne isso: é uma proteção contra quem abre um PR só para roubar a chave.",
      "Sempre que possível, troque credenciais de longa duração por credenciais temporárias. Os principais provedores de nuvem aceitam o OIDC do GitHub Actions: o pipeline prova quem é e recebe uma credencial que expira em minutos, sem nenhuma chave guardada.",
      "Dê ao pipeline o menor privilégio: um pipeline que só publica uma imagem não precisa de permissão para apagar o banco.",
    ] },
    { tipo: "dica", titulo: "A pergunta que resolve a maioria dos casos", texto: "Para qualquer segredo, pergunte: onde ele está agora, quem consegue lê-lo, e o que eu faria se ele vazasse hoje? Se a resposta para a última pergunta for entrar em pânico, falta uma rotina de rotação e um plano." },

    { tipo: "h", texto: "Dependências: o código que você não escreveu" },
    { tipo: "p", texto: "Em um projeto típico, a maior parte do código executado vem de bibliotecas de terceiros, e cada uma traz as suas próprias dependências. Isso é ótimo para produtividade e uma enorme superfície de risco. Dois problemas diferentes aparecem aqui." },
    { tipo: "h3", texto: "Vulnerabilidades conhecidas" },
    { tipo: "p", texto: "Quando alguém descobre uma falha em uma biblioteca, ela recebe um identificador público, o CVE, e as bases de dados de vulnerabilidades registram quais versões são afetadas. Se o seu projeto usa uma versão afetada, ele herda o problema." },
    { tipo: "p", texto: "Existem ferramentas que comparam as suas dependências com essas bases:" },
    { tipo: "tabela", cabecalho: ["Ecossistema", "Ferramenta", "Como rodar"], linhas: [
      ["Node", "npm audit", "npm audit"],
      ["Python", "pip-audit", "pip-audit"],
      ["Java (Maven)", "OWASP Dependency-Check", "mvn org.owasp:dependency-check-maven:check"],
      ["Qualquer", "Dependabot, Renovate", "Abrem pull requests de atualização automaticamente"],
    ] },
    { tipo: "p", texto: "Nem todo alerta é urgente. Um aviso só importa se o código vulnerável é realmente usado pelo seu projeto, e a gravidade depende do contexto. Mas alertas altos e críticos com correção disponível devem entrar no planejamento." },
    { tipo: "h3", texto: "Ataques à cadeia de suprimentos" },
    { tipo: "p", texto: "O segundo problema é a biblioteca ser maliciosa, ou ficar maliciosa depois. Alguns padrões que já aconteceram:" },
    { tipo: "lista", itens: [
      "Typosquatting: um pacote com nome parecido com o de um popular (reqeusts em vez de requests) para pegar quem erra a digitação.",
      "Confusão de dependência: um pacote público com o mesmo nome de um pacote interno da empresa, que acaba sendo instalado no lugar dele.",
      "Contas de mantenedores invadidas, que publicam uma versão com código malicioso.",
      "Scripts de instalação (postinstall, em npm) que executam código na máquina de quem instala.",
    ] },
    { tipo: "h3", texto: "Hábitos que reduzem o risco" },
    { tipo: "numerada", itens: [
      "Versione o arquivo de bloqueio (package-lock.json, poetry.lock, requirements com versões fixas). Ele garante que todos instalam exatamente as mesmas versões.",
      "Na integração contínua, instale com o comando que respeita o arquivo de bloqueio (npm ci, por exemplo), e não com o que o reescreve.",
      "Antes de adicionar uma dependência, olhe: é mantida? Tem muitos usuários? Faz muito mais do que você precisa? Às vezes dez linhas de código próprias são mais seguras do que um pacote.",
      "Revise o que muda em uma atualização, principalmente as grandes. Atualizações automáticas são bem-vindas, mas passam por revisão e testes.",
      "Evite executar scripts baixados e passados direto para o shell (curl ... | bash) sem ler antes.",
      "Remova o que não usa. Dependência que não existe não tem vulnerabilidade.",
    ] },

    { tipo: "h", texto: "Logs: o que registrar e o que nunca registrar" },
    { tipo: "p", texto: "Logs são a memória do sistema. Sem eles, é impossível descobrir um ataque, entender um defeito ou provar o que aconteceu. Com eles mal feitos, viram um segundo vazamento: um arquivo de texto cheio de senhas e dados pessoais, geralmente com muito menos proteção do que o banco." },
    { tipo: "h3", texto: "O que vale registrar" },
    { tipo: "lista", itens: [
      "Eventos de autenticação: logins bem-sucedidos e falhos, trocas de senha, uso de MFA.",
      "Falhas de autorização: tentativas de acessar o que não pode.",
      "Falhas de validação em volume incomum, que podem indicar varredura.",
      "Ações administrativas e alterações de permissão.",
      "Erros de aplicação, com contexto suficiente para diagnosticar.",
    ] },
    { tipo: "h3", texto: "O que nunca vai para o log" },
    { tipo: "lista", itens: [
      "Senhas, tokens, chaves de API, identificadores de sessão e cookies.",
      "Dados de cartão e outros dados financeiros.",
      "Documentos e dados pessoais além do necessário (CPF, endereço completo, dados de saúde). A LGPD se aplica também aos logs.",
      "O corpo inteiro de requisições e respostas, sem filtrar.",
    ] },
    { tipo: "codigo", linguagem: "typescript", legenda: "pino com redação de campos sensíveis", texto: "import pino from \"pino\";\n\nexport const logger = pino({\n  redact: {\n    paths: [\n      \"req.headers.authorization\",\n      \"req.headers.cookie\",\n      \"senha\",\n      \"*.senha\",\n      \"*.token\",\n    ],\n    censor: \"[removido]\",\n  },\n});\n\nlogger.info({ usuarioId: 42, rota: \"/login\" }, \"login bem-sucedido\");" },
    { tipo: "alerta", titulo: "Cuidado com toString e objetos inteiros", texto: "Em Java, registrar um objeto com log.info(\"usuario={}\", usuario) chama o toString, que pode incluir campos sensíveis. Em Python, registrar request.__dict__ ou o corpo da requisição faz o mesmo. Registre campos escolhidos, não objetos inteiros." },
    { tipo: "h3", texto: "Injeção de log" },
    { tipo: "p", texto: "Se o log é escrito em texto puro e você registra um valor controlado pelo usuário, ele pode incluir uma quebra de linha e forjar uma linha falsa no arquivo (por exemplo, um \"login bem-sucedido\" que nunca aconteceu). Duas defesas: usar logs estruturados em JSON, em que cada valor fica dentro de um campo, e remover ou escapar quebras de linha de valores externos." },
    { tipo: "h3", texto: "Boas práticas" },
    { tipo: "lista", itens: [
      "Logs estruturados (JSON): ficam pesquisáveis e seguros contra injeção.",
      "Níveis usados com critério (debug, info, warn, error) e nível debug desligado em produção.",
      "Um identificador de correlação por requisição, para seguir uma chamada por vários serviços.",
      "Retenção definida: guardar o suficiente para investigar, não para sempre.",
      "Alguém ou algo olha: de nada adianta registrar um ataque se nenhum alerta o percebe.",
    ] },

    { tipo: "h", texto: "Erros para o cliente × erros para você" },
    { tipo: "p", texto: "Quem faz a requisição e quem opera o sistema precisam de informações diferentes. O cliente precisa saber o que fazer (corrigir um campo, tentar de novo mais tarde). Quem opera precisa do contexto completo. Misturar os dois vaza detalhes internos." },
    { tipo: "tabela", cabecalho: ["", "Para o cliente", "Para o log"], linhas: [
      ["Erro de validação", "Qual campo está errado e por quê.", "O mesmo, mais o identificador da requisição."],
      ["Item inexistente", "404 com mensagem fixa.", "Quem pediu e qual identificador."],
      ["Falha inesperada (500)", "Mensagem genérica e, no máximo, um código de ocorrência.", "A exceção completa, com stack trace."],
      ["Falha de autenticação", "\"E-mail ou senha inválidos\".", "O motivo real e a origem da tentativa."],
    ] },
    { tipo: "codigo", linguagem: "python", legenda: "FastAPI: tratador global de erros", texto: "import logging\nimport uuid\n\nfrom fastapi import Request\nfrom fastapi.responses import JSONResponse\n\nlogger = logging.getLogger(__name__)\n\n\n@app.exception_handler(Exception)\nasync def erro_inesperado(request: Request, exc: Exception):\n    ocorrencia = uuid.uuid4().hex[:8]\n    logger.exception(\"erro inesperado ocorrencia=%s rota=%s\", ocorrencia, request.url.path)\n    return JSONResponse(\n        status_code=500,\n        content={\"erro\": \"Erro interno do servidor\", \"ocorrencia\": ocorrencia},\n    )" },
    { tipo: "p", texto: "O cliente recebe só um código curto de ocorrência. Se ele reportar o problema, quem opera procura esse código no log e encontra a stack trace completa." },

    { tipo: "h", texto: "Configuração segura" },
    { tipo: "p", texto: "Muitos problemas de segurança vêm de configurações padrão que ninguém revisou. Vale um olhar antes de cada implantação em produção:" },
    { tipo: "tabela", cabecalho: ["Item", "Em desenvolvimento", "Em produção"], linhas: [
      ["Modo de depuração (DEBUG do Django e do Flask, devtools do Spring)", "Pode ligar", "Sempre desligado"],
      ["Mensagens de erro", "Detalhadas", "Genéricas"],
      ["Contas e senhas padrão", "Podem existir localmente", "Nenhuma: troque ou remova"],
      ["Painéis de administração", "Locais", "Atrás de autenticação forte e, se possível, de rede restrita"],
      ["HTTPS", "Opcional", "Obrigatório, com redirecionamento e HSTS"],
      ["Portas e serviços (banco, cache)", "Abertos na máquina", "Acessíveis só pela rede interna"],
      ["Listagem de diretórios e arquivos de backup no servidor web", "Irrelevante", "Desligada e removidos"],
      ["Permissões em armazenamento na nuvem", "Privadas", "Privadas por padrão, públicas só com motivo"],
    ] },
    { tipo: "dica", titulo: "Faça a configuração ser segura por padrão", texto: "Em vez de depender de alguém lembrar de desligar a depuração, faça o contrário: o padrão do código é o modo seguro, e o modo de depuração só liga com uma variável explícita no ambiente de desenvolvimento. Se a variável sumir, o sistema fica seguro, não exposto." },

    { tipo: "h", texto: "Uma lista de conferência antes de publicar" },
    { tipo: "numerada", itens: [
      "Há algum segredo no código ou no histórico do repositório? O .env está no .gitignore?",
      "As dependências foram verificadas por uma ferramenta de auditoria? Há atualizações críticas pendentes?",
      "O arquivo de bloqueio está versionado e o pipeline o respeita?",
      "O modo de depuração está desligado e as mensagens de erro são genéricas?",
      "Os logs registram eventos de segurança sem registrar segredos e dados pessoais?",
      "Cada ambiente tem segredos próprios, com o menor privilégio possível?",
      "O banco e os demais serviços só são acessíveis pela rede interna?",
      "Existe um plano, mesmo curto, para o caso de um segredo vazar?",
    ] },
  ],
  exercicios: [
    "Rode o gitleaks no seu repositório, incluindo o histórico. Encontrou algo? Se sim, o que você faria em ordem?",
    "Crie o .env.example do seu projeto e confirme que o .env está no .gitignore. Peça a alguém para clonar e subir o projeto só com esse arquivo.",
    "Rode o npm audit, o pip-audit ou o dependency-check no seu projeto. Classifique os resultados em urgentes e não urgentes e justifique.",
    "Procure no código todo log que escreve um objeto inteiro ou um corpo de requisição. Troque por campos escolhidos.",
    "Provoque um erro inesperado em uma rota e olhe a resposta. Ela mostra algum detalhe interno? Corrija e confirme que o detalhe foi para o log.",
  ],
  referencias: [
    { titulo: "OWASP: Secrets Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html" },
    { titulo: "OWASP: Logging Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html" },
    { titulo: "OWASP: Vulnerable Dependency Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerable_Dependency_Management_Cheat_Sheet.html" },
    { titulo: "OWASP: Error Handling Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html" },
    { titulo: "GitHub: sobre a varredura de segredos", url: "https://docs.github.com/pt/code-security/secret-scanning/introduction/about-secret-scanning" },
  ],
};
