import type { Aula } from "./tipos";

export const AULA_AUTENTICACAO: Aula = {
  slug: "autenticacao-e-autorizacao-senhas-sessoes-e-acesso",
  titulo: "Autenticação e autorização: senhas, sessões, tokens e controle de acesso",
  resumo: "Como guardar senhas, escolher entre sessão e JWT, montar um login seguro e garantir que cada pessoa só acesse o que é dela.",
  trilha: "seguranca",
  nivel: "Intermediário",
  leitura: "24 min",
  preRequisitos: [
    "Entender o que é um cookie e um cabeçalho HTTP.",
    "Ter feito, ao menos uma vez, uma rota que devolve dados de um banco.",
  ],
  pontosChave: [
    "Autenticar é provar quem você é. Autorizar é decidir o que você pode fazer. São etapas diferentes e as duas precisam existir em toda requisição.",
    "Senhas nunca são guardadas: guarda-se o hash lento (Argon2id, bcrypt, scrypt) com sal, gerado pela biblioteca.",
    "Sessão com cookie HttpOnly e token JWT têm vantagens e riscos distintos. Escolha sabendo o porquê.",
    "A maior falha do mundo real é de autorização: a pessoa está logada, mas acessa o dado de outra. Confira o dono do recurso no servidor.",
    "Mensagens de erro de login devem ser genéricas e as tentativas devem ter limite.",
  ],
  blocos: [
    { tipo: "p", texto: "Quase todo sistema real precisa saber quem está do outro lado e o que essa pessoa pode fazer. Esses dois problemas parecem um só, e essa confusão é a origem de muitas falhas. Este artigo separa os dois, mostra os padrões que funcionam e os erros que aparecem toda semana em revisões de código." },

    { tipo: "h", texto: "Autenticação e autorização não são a mesma coisa" },
    { tipo: "tabela", cabecalho: ["", "Autenticação (authN)", "Autorização (authZ)"], linhas: [
      ["A pergunta", "Quem é você?", "O que você pode fazer?"],
      ["Quando acontece", "No login e a cada requisição (a sessão ou o token prova a identidade)", "Em toda ação, em toda requisição"],
      ["Resposta de falha", "401: não identificado", "403 ou 404: identificado, mas sem permissão"],
      ["Exemplo", "Conferir a senha, validar o token", "Esse pedido é do usuário? Ele é administrador?"],
    ] },
    { tipo: "p", texto: "Um erro comum é achar que, se o usuário está logado, está tudo certo. Estar logado só responde à primeira pergunta. A segunda precisa ser respondida de novo para cada recurso que a pessoa tenta acessar." },

    { tipo: "h", texto: "Guardando senhas do jeito certo" },
    { tipo: "p", texto: "A regra número um: o sistema nunca deve conseguir ler a senha de um usuário. Se um banco de dados vazar, o que estiver nele já é considerado público, então ele não pode conter senhas, só uma forma delas que não possa ser revertida." },
    { tipo: "h3", texto: "Por que não criptografar nem usar um hash qualquer" },
    { tipo: "lista", itens: [
      "Texto puro: qualquer vazamento expõe todas as senhas, e as pessoas reutilizam senhas em outros sites.",
      "Criptografia reversível: quem tiver a chave (e ela costuma estar no mesmo servidor) recupera tudo.",
      "Hashes rápidos como MD5, SHA-1 e até SHA-256 puro: foram feitos para serem rápidos, e quem rouba a base consegue testar bilhões de palpites por segundo.",
    ] },
    { tipo: "h3", texto: "O que usar" },
    { tipo: "p", texto: "Funções de derivação de chave feitas para senhas: lentas de propósito, com custo ajustável e sal aleatório embutido. As recomendadas hoje são o Argon2id, o bcrypt e o scrypt. O PBKDF2 também é aceito, principalmente quando há exigência de conformidade." },
    { tipo: "dica", titulo: "O que é o sal", texto: "Um valor aleatório gerado para cada senha e guardado junto do hash. Ele garante que duas pessoas com a mesma senha tenham hashes diferentes e impede o uso de tabelas pré-calculadas. As bibliotecas boas geram e guardam o sal sozinhas: você não precisa (e não deve) cuidar disso." },
    { tipo: "codigo", linguagem: "java", legenda: "Java, com Spring Security", texto: "PasswordEncoder encoder = new BCryptPasswordEncoder(12);\n\nString hash = encoder.encode(senhaEmTextoPuro);   // ao cadastrar\nboolean confere = encoder.matches(senhaDigitada, hash); // ao entrar" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Node, com bcrypt", texto: "import bcrypt from \"bcrypt\";\n\nconst hash = await bcrypt.hash(senha, 12);            // ao cadastrar\nconst confere = await bcrypt.compare(senhaDigitada, hash); // ao entrar" },
    { tipo: "codigo", linguagem: "python", legenda: "Python, com argon2-cffi", texto: "from argon2 import PasswordHasher\nfrom argon2.exceptions import VerifyMismatchError\n\nph = PasswordHasher()\n\nhash_da_senha = ph.hash(senha)  # ao cadastrar\n\ntry:\n    ph.verify(hash_da_senha, senha_digitada)  # ao entrar\n    confere = True\nexcept VerifyMismatchError:\n    confere = False" },
    { tipo: "p", texto: "O número 12 no bcrypt é o fator de custo: cada aumento de uma unidade dobra o tempo. O valor certo é o maior que o seu servidor aguenta sem deixar o login lento, e deve ser revisto com o tempo, conforme o hardware evolui." },
    { tipo: "alerta", titulo: "Limite do bcrypt", texto: "O bcrypt considera apenas os primeiros 72 bytes da senha. Para a maioria dos casos isso é irrelevante, mas, se a sua aplicação aceita senhas muito longas, saiba que o que passar desse tamanho é ignorado." },
    { tipo: "h3", texto: "Sobre as regras de senha" },
    { tipo: "p", texto: "As recomendações do NIST (SP 800-63B) mudaram o que se considerava boa prática: tamanho vale mais do que complexidade. Em vez de exigir uma maiúscula, um número e um símbolo, permita senhas longas (inclusive frases), aceite todos os caracteres, recuse senhas conhecidas por terem vazado e evite forçar a troca periódica sem motivo. Mostrar um medidor de força ajuda mais do que regras arbitrárias." },

    { tipo: "h", texto: "Sessão ou token? Como o sistema lembra quem você é" },
    { tipo: "p", texto: "O HTTP não guarda memória entre requisições. Depois do login, o sistema precisa de uma forma de reconhecer a pessoa nas próximas chamadas. Existem dois caminhos principais." },
    { tipo: "h3", texto: "Sessão no servidor" },
    { tipo: "p", texto: "Depois do login, o servidor cria um registro (a sessão) com os dados do usuário e entrega ao navegador um identificador aleatório, em um cookie. A cada requisição, o navegador devolve o cookie e o servidor busca a sessão. Para encerrar, basta apagar o registro." },
    { tipo: "lista", itens: [
      "Vantagem: o servidor controla tudo. Encerrar a sessão ou bloquear um usuário tem efeito imediato.",
      "Custo: o servidor precisa guardar as sessões (em memória, banco ou Redis), o que complica a escala horizontal.",
    ] },
    { tipo: "h3", texto: "Token assinado (JWT)" },
    { tipo: "p", texto: "O JWT (JSON Web Token) é um token que carrega dados (as claims) e uma assinatura. O servidor não precisa guardar nada: ao receber o token, confere a assinatura e confia no conteúdo." },
    { tipo: "lista", itens: [
      "Vantagem: sem estado no servidor, bom para várias instâncias e para APIs consumidas por aplicativos e outros serviços.",
      "Custo: não dá para invalidar um token antes de ele expirar, a não ser que o servidor mantenha uma lista de bloqueio, o que traz o estado de volta.",
    ] },
    { tipo: "alerta", titulo: "JWT não é criptografado, é assinado", texto: "O conteúdo de um JWT é só codificado em base64url: qualquer pessoa que o veja consegue ler as claims. A assinatura garante que não foi alterado, não que é secreto. Nunca coloque senha, dado pessoal sensível ou segredo dentro de um token." },
    { tipo: "h3", texto: "Cuidados ao usar JWT" },
    { tipo: "lista", itens: [
      "Validar tudo: assinatura, expiração (exp), emissor (iss) e destinatário (aud). Use a biblioteca para isso, não confira à mão.",
      "Fixar o algoritmo esperado no servidor. Ataques históricos exploraram servidores que aceitavam o algoritmo que o próprio token declarava (inclusive \"none\").",
      "Vida curta: tokens de acesso devem expirar em minutos. Para manter a pessoa logada, use um refresh token, guardado com mais cuidado e renovado a cada uso (rotação).",
      "Onde guardar no navegador: o localStorage é lido por qualquer script da página, então uma falha de XSS entrega o token. Um cookie HttpOnly não pode ser lido por scripts.",
    ] },
    { tipo: "h3", texto: "Qual escolher" },
    { tipo: "p", texto: "Para uma aplicação web que tem uma interface própria no navegador, a sessão com cookie HttpOnly costuma ser a escolha mais simples e mais segura. É o que o próprio projeto Koda usa: um cookie de sessão HttpOnly e SameSite=Lax, e o servidor guarda a sessão. Tokens fazem mais sentido quando há aplicativos móveis, integrações entre serviços ou necessidade de escalar sem estado, e ainda assim exigem os cuidados acima." },

    { tipo: "h3", texto: "As opções de um cookie de sessão" },
    { tipo: "tabela", cabecalho: ["Opção", "O que faz", "Quando usar"], linhas: [
      ["HttpOnly", "Impede que scripts da página leiam o cookie.", "Sempre, em cookies de sessão."],
      ["Secure", "O cookie só viaja por HTTPS.", "Sempre em produção."],
      ["SameSite=Lax", "Não envia o cookie em requisições de outros sites, exceto navegação por link.", "Padrão recomendado. Ajuda contra CSRF."],
      ["SameSite=Strict", "Não envia o cookie em nenhuma requisição vinda de outro site.", "Quando o usuário nunca chega ao sistema por links externos."],
      ["Prefixo __Host-", "Exige Secure, caminho / e nenhum domínio explícito.", "Para travar o escopo do cookie."],
    ] },
    { tipo: "codigo", linguagem: "http", legenda: "Exemplo de cabeçalho de resposta", texto: "Set-Cookie: __Host-sessao=3f9c...; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=3600" },

    { tipo: "h", texto: "Um login seguro, passo a passo" },
    { tipo: "numerada", itens: [
      "Buscar o usuário pelo identificador (e-mail) com uma consulta parametrizada.",
      "Conferir o hash da senha com a função da biblioteca. Mesmo quando o usuário não existe, faça uma conferência fictícia contra um hash qualquer, para o tempo de resposta não revelar quais e-mails existem.",
      "Em caso de falha, responder sempre com a mesma mensagem genérica: \"E-mail ou senha inválidos\". Nunca diga qual dos dois estava errado.",
      "Em caso de sucesso, gerar um novo identificador de sessão (regenerar o id): se o antigo ficasse valendo, seria possível uma fixação de sessão, em que o atacante define o id e espera a vítima entrar.",
      "Registrar o evento (sucesso e falha), sem a senha.",
    ] },
    { tipo: "h3", texto: "Limite de tentativas" },
    { tipo: "p", texto: "Sem limite, um atacante testa milhares de senhas, ou aproveita senhas vazadas de outros sites (credential stuffing). Defesas: limitar tentativas por conta e por endereço, aumentar o atraso a cada falha, bloquear temporariamente e avisar o dono da conta. Cuidado para não criar uma forma de negar o acesso a qualquer pessoa, bloqueando contas só por tentativas de terceiros: o bloqueio temporário e com atraso é melhor do que o definitivo." },
    { tipo: "h3", texto: "Autenticação de múltiplos fatores (MFA)" },
    { tipo: "p", texto: "Pedir um segundo fator (um código de aplicativo autenticador, uma chave de segurança) corta a maioria dos ataques por senha vazada. Prefira aplicativos autenticadores e chaves FIDO2/WebAuthn a códigos por SMS, que podem ser desviados. E exija o fator de novo antes de ações sensíveis, como trocar a senha ou o e-mail." },
    { tipo: "h3", texto: "Recuperação de senha" },
    { tipo: "p", texto: "É o ponto mais fraco de muitos sistemas. Regras: o token enviado por e-mail deve ser aleatório e longo, de uso único, com validade curta e guardado como hash no banco, como uma senha. A resposta do pedido de recuperação deve ser a mesma exista ou não o e-mail (\"se o e-mail existir, enviaremos instruções\"). E depois da troca, encerre as outras sessões." },
    { tipo: "h3", texto: "Logout de verdade" },
    { tipo: "p", texto: "Sair deve apagar a sessão no servidor, não apenas o cookie no navegador. Com JWT, isso significa registrar o token (ou a sua família de refresh) como revogado, ou aceitar que ele valerá até expirar, e por isso mantê-lo de vida curta." },

    { tipo: "h", texto: "Autorização: cada pessoa só acessa o que é dela" },
    { tipo: "p", texto: "Aqui estão as falhas mais comuns do mundo real. O sistema sabe quem é o usuário, mas esquece de conferir se ele pode fazer aquela ação naquele recurso." },
    { tipo: "h3", texto: "Os modelos mais usados" },
    { tipo: "lista", itens: [
      "RBAC (controle por papéis): o usuário tem papéis (admin, gerente, cliente) e cada rota exige um papel.",
      "Por propriedade (ownership): o recurso tem um dono, e só ele (ou quem ele autorizou) pode acessá-lo.",
      "ABAC (por atributos): a decisão considera atributos do usuário, do recurso e do contexto (horário, local, status do pedido).",
    ] },
    { tipo: "p", texto: "Na prática, a maioria dos sistemas combina papéis para as áreas administrativas com propriedade para os dados dos usuários." },
    { tipo: "h3", texto: "IDOR / BOLA: a falha número 1" },
    { tipo: "p", texto: "Imagine GET /pedidos/42. Se o servidor busca o pedido 42 e devolve sem conferir de quem é, qualquer usuário logado lê qualquer pedido, basta mudar o número. O nome técnico é referência direta insegura a objeto (IDOR), ou Broken Object Level Authorization (BOLA) na lista de segurança de APIs da OWASP." },
    { tipo: "p", texto: "A correção é incluir o dono na própria consulta, de forma que um recurso alheio simplesmente não seja encontrado:" },
    { tipo: "codigo", linguagem: "python", legenda: "FastAPI: o dono faz parte da busca", texto: "from fastapi import Depends, HTTPException\n\n\n@app.get(\"/pedidos/{pedido_id}\")\ndef buscar(pedido_id: int, usuario: Usuario = Depends(usuario_atual)):\n    pedido = repositorio.buscar_do_usuario(pedido_id, usuario.id)\n    if pedido is None:\n        raise HTTPException(status_code=404, detail=\"Pedido não encontrado\")\n    return pedido" },
    { tipo: "codigo", linguagem: "java", legenda: "Spring: papel na rota, dono no serviço", texto: "@PreAuthorize(\"hasRole('ADMIN')\")\n@GetMapping(\"/admin/relatorios\")\npublic List<Relatorio> relatorios() { ... }\n\n// No serviço: o dono entra na consulta\npublic PedidoResposta buscar(Long id, Long usuarioId) {\n    Pedido pedido = repository.findByIdAndUsuarioId(id, usuarioId)\n            .orElseThrow(() -> new PedidoNaoEncontradoException(id));\n    return PedidoResposta.de(pedido);\n}" },
    { tipo: "p", texto: "Repare no retorno 404, e não 403, para um pedido que existe mas é de outra pessoa. Responder 403 confirma que o pedido existe, o que já é uma informação. Devolver 404 nos dois casos (não existe ou não é seu) evita que alguém varra identificadores para descobrir quais existem. Para ações em que a pessoa claramente deveria saber que existe uma restrição, como acessar uma área administrativa, o 403 é mais claro. O importante é decidir de forma consistente." },
    { tipo: "dica", titulo: "Identificadores imprevisíveis ajudam, mas não substituem", texto: "Usar UUID em vez de números sequenciais torna mais difícil adivinhar um identificador, mas não é controle de acesso. Se alguém conseguir um UUID (por um link compartilhado, por exemplo), o servidor ainda precisa conferir se aquela pessoa pode acessá-lo." },
    { tipo: "h3", texto: "Atribuição em massa (mass assignment)" },
    { tipo: "p", texto: "Outra falha de autorização disfarçada: o código copia todos os campos do corpo da requisição para o objeto, e o usuário envia um campo extra, como \"papel\": \"admin\". Defina explicitamente quais campos podem ser alterados (um DTO com só os campos permitidos) em vez de aceitar tudo." },
    { tipo: "codigo", linguagem: "typescript", legenda: "Aceite só o que é esperado", texto: "// Vulnerável: o usuário pode enviar { \"papel\": \"admin\" }\nawait Usuario.update(req.body, { where: { id: req.usuario.id } });\n\n// Correto: só campos conhecidos\nconst { nome, telefone } = req.body;\nawait Usuario.update({ nome, telefone }, { where: { id: req.usuario.id } });" },
    { tipo: "h3", texto: "Negar por padrão e conferir no servidor" },
    { tipo: "lista", itens: [
      "Esconder um botão não protege nada: a rota por trás dele precisa conferir a permissão.",
      "Prefira uma configuração em que toda rota exige login e permissão, e as exceções (login, páginas públicas) são listadas. Assim, uma rota nova esquecida nasce fechada, e não aberta.",
      "Concentre a lógica de permissão em poucos lugares (um filtro, uma política, uma função), em vez de espalhar if por todo o código.",
    ] },

    { tipo: "h", texto: "Erros comuns" },
    { tipo: "tabela", cabecalho: ["Erro", "Por que é um problema", "O que fazer"], linhas: [
      ["Conferir permissão só no front-end", "Qualquer um chama a API direto.", "Conferir sempre no servidor."],
      ["Mensagens diferentes para e-mail e senha errados", "Revela quais e-mails têm conta.", "Mensagem única e genérica."],
      ["Token ou id de sessão na URL", "Vai para logs, histórico e cabeçalho Referer.", "Cookie ou cabeçalho Authorization."],
      ["Sem limite de tentativas", "Permite adivinhar senhas em massa.", "Limite e atraso por conta e por origem."],
      ["JWT de longa duração no localStorage", "Roubado por XSS e impossível de revogar.", "Vida curta, cookie HttpOnly, rotação."],
      ["Papel do usuário vindo do corpo da requisição", "O usuário se promove sozinho.", "Ler papéis do servidor, nunca da entrada."],
      ["Reutilizar a mesma chave de assinatura em todos os ambientes", "Um vazamento em teste compromete a produção.", "Chaves diferentes por ambiente."],
    ] },

    { tipo: "h", texto: "Testando a autorização" },
    { tipo: "p", texto: "Falhas de autorização não aparecem em teste de caminho feliz: o dono sempre consegue ver o que é dele. É preciso testar o caminho em que a pessoa errada tenta. Um bom conjunto cobre, para cada recurso, quatro cenários: sem login, logado como dono, logado como outra pessoa e logado como administrador." },
    { tipo: "codigo", linguagem: "java", legenda: "Spring MockMvc", texto: "@Test\nvoid naoDeveDevolverOPedidoDeOutraPessoa() throws Exception {\n    Pedido pedidoDaAna = criarPedidoDe(\"ana\");\n\n    mockMvc.perform(get(\"/pedidos/\" + pedidoDaAna.getId()).with(user(\"bia\")))\n            .andExpect(status().isNotFound());\n}\n\n@Test\nvoid deveExigirLogin() throws Exception {\n    mockMvc.perform(get(\"/pedidos/1\"))\n            .andExpect(status().isUnauthorized());\n}" },
    { tipo: "codigo", linguagem: "python", legenda: "pytest com TestClient", texto: "def test_nao_devolve_pedido_de_outra_pessoa(cliente, token_da_bia, pedido_da_ana):\n    resposta = cliente.get(\n        f\"/pedidos/{pedido_da_ana.id}\",\n        headers={\"Authorization\": f\"Bearer {token_da_bia}\"},\n    )\n\n    assert resposta.status_code == 404\n\n\ndef test_exige_login(cliente):\n    assert cliente.get(\"/pedidos/1\").status_code == 401" },
  ],
  exercicios: [
    "Confira como o seu projeto guarda senhas. Se não usa um hash lento com sal, troque e planeje a migração dos usuários existentes (por exemplo, re-hashear no próximo login).",
    "Escolha cinco rotas do projeto e, para cada uma, escreva os quatro testes: sem login, dono, outra pessoa e administrador.",
    "Procure um lugar onde o papel ou o id do dono vem do corpo ou da URL. Ele deveria vir da sessão?",
    "Abra as ferramentas do navegador, olhe o cookie de sessão do seu sistema e confira se tem HttpOnly, Secure e SameSite.",
    "Adicione um limite de tentativas de login e teste que a sexta tentativa seguida é recusada, mesmo com a senha certa.",
  ],
  referencias: [
    { titulo: "OWASP: Password Storage Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html" },
    { titulo: "OWASP: Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" },
    { titulo: "OWASP: Session Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
    { titulo: "OWASP: Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" },
    { titulo: "OWASP: JSON Web Token Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_Cheat_Sheet.html" },
    { titulo: "MDN: Cookies HTTP", url: "https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Cookies" },
    { titulo: "NIST SP 800-63B: Digital Identity Guidelines", url: "https://pages.nist.gov/800-63-3/sp800-63b.html" },
  ],
};
