import type { Aula } from "./tipos";

export const AULA_INJECAO: Aula = {
  slug: "injecao-de-sql-como-acontece-e-como-evitar",
  titulo: "Injeção de SQL: como acontece e como evitar, em Java, Node e Python",
  resumo: "Por que concatenar texto em uma consulta é perigoso, como as consultas parametrizadas resolvem e o que elas não cobrem.",
  trilha: "seguranca",
  nivel: "Júnior",
  leitura: "20 min",
  preRequisitos: [
    "Saber escrever uma consulta SQL com SELECT e WHERE.",
    "Ter usado um driver de banco ou um ORM em Java, Node ou Python.",
  ],
  pontosChave: [
    "A injeção acontece quando dado do usuário vira parte do comando, e não apenas um valor.",
    "A defesa principal é a consulta parametrizada: comando e valores viajam separados.",
    "Parâmetros não valem para nomes de tabela, coluna ou ORDER BY: para esses, use uma lista permitida.",
    "ORMs ajudam, mas consultas nativas e filtros montados com a entrada voltam a abrir a porta.",
    "O usuário do banco deve ter só as permissões que a aplicação precisa.",
  ],
  blocos: [
    { tipo: "p", texto: "A injeção de SQL existe há mais de vinte anos, é bem compreendida e ainda aparece em sistemas novos. A razão é simples: a forma errada de escrever a consulta é a mais intuitiva, e ela funciona nos testes do dia a dia. Só falha quando alguém envia o que ninguém esperava." },

    { tipo: "h", texto: "Injeção em geral: dado que vira comando" },
    { tipo: "p", texto: "Injeção é um nome para uma família de falhas com a mesma causa: um programa monta um comando juntando texto fixo com texto do usuário, e entrega o resultado para um interpretador. Se o interpretador não consegue distinguir o que era comando do que era dado, o usuário pode escrever comando." },
    { tipo: "p", texto: "O interpretador pode ser um banco SQL, um banco NoSQL, o shell do sistema operacional, um servidor LDAP, um mecanismo de templates. Este artigo foca em SQL, que é onde o problema é mais comum, e mostra o paralelo com NoSQL mais adiante." },

    { tipo: "h", texto: "Como a injeção de SQL acontece" },
    { tipo: "p", texto: "Imagine um login que confere o e-mail e a senha, escrito em Python com concatenação de texto:" },
    { tipo: "codigo", linguagem: "python", legenda: "Versão vulnerável", texto: "def buscar_usuario(conn, email, senha):\n    consulta = (\n        \"SELECT id, email FROM usuarios \"\n        \"WHERE email = '\" + email + \"' AND senha = '\" + senha + \"'\"\n    )\n    return conn.execute(consulta).fetchone()" },
    { tipo: "p", texto: "Com entradas normais, a consulta final é uma frase de SQL válida:" },
    { tipo: "codigo", linguagem: "sql", texto: "SELECT id, email FROM usuarios WHERE email = 'ana@exemplo.com' AND senha = 'abc123'" },
    { tipo: "p", texto: "Agora imagine que alguém digite, no campo de e-mail, o texto ana@exemplo.com' -- . As aspas simples fecham o valor antes da hora, e os dois traços iniciam um comentário em SQL. A consulta que chega ao banco passa a ser:" },
    { tipo: "codigo", linguagem: "sql", texto: "SELECT id, email FROM usuarios WHERE email = 'ana@exemplo.com' -- ' AND senha = ''" },
    { tipo: "p", texto: "Tudo depois dos traços é ignorado, inclusive a conferência da senha. A pessoa entra como Ana sem saber a senha. Outro exemplo clássico é digitar ' OR '1'='1 em um campo: a condição passa a ser sempre verdadeira, e a consulta devolve todos os registros." },
    { tipo: "alerta", titulo: "O problema não é o apóstrofo", texto: "Alguns iniciantes tentam resolver proibindo certos caracteres. Isso não funciona: nomes legítimos têm apóstrofo (D'Ávila, O'Brien) e há muitas outras formas de montar uma entrada maliciosa. A solução é fazer com que o texto do usuário nunca seja interpretado como comando, e isso se faz pela estrutura da consulta, não por filtro de caracteres." },

    { tipo: "h3", texto: "O que um atacante consegue" },
    { tipo: "lista", itens: [
      "Contornar a autenticação, como no exemplo acima.",
      "Ler dados que não deveria: outras contas, senhas, dados pessoais, ou o próprio esquema do banco.",
      "Alterar ou apagar dados.",
      "Em configurações permissivas, chegar a executar comandos no servidor do banco.",
    ] },
    { tipo: "p", texto: "O estrago depende do que a conta do banco usada pela aplicação pode fazer. Voltaremos a isso na seção sobre menor privilégio." },

    { tipo: "h3", texto: "Variações que você vai ouvir citar" },
    { tipo: "lista", itens: [
      "Baseada em erro: a aplicação mostra a mensagem de erro do banco, e ela revela informação sobre a consulta e o esquema.",
      "Cega (blind): a aplicação não mostra nada, mas o atacante deduz informação pela diferença de comportamento (resposta diferente, demora diferente).",
      "De segunda ordem: o dado malicioso é gravado de forma segura, mas lido e usado depois, em outra consulta montada com concatenação.",
    ] },

    { tipo: "h", texto: "A defesa principal: consultas parametrizadas" },
    { tipo: "p", texto: "Em uma consulta parametrizada, o comando é enviado ao banco com marcadores no lugar dos valores, e os valores vão separados. O banco primeiro entende a estrutura do comando e só depois encaixa os valores como dados. Não importa o que o valor contenha: ele nunca é reinterpretado como parte do comando." },
    { tipo: "p", texto: "A mesma ideia aparece em todas as linguagens, só muda a sintaxe do marcador." },

    { tipo: "h3", texto: "Python" },
    { tipo: "codigo", linguagem: "python", legenda: "sqlite3: o marcador é ?", texto: "def buscar_usuario(conn, email):\n    cursor = conn.execute(\n        \"SELECT id, email FROM usuarios WHERE email = ?\",\n        (email,),\n    )\n    return cursor.fetchone()" },
    { tipo: "codigo", linguagem: "python", legenda: "psycopg (PostgreSQL): o marcador é %s", texto: "def buscar_pedido(conexao, pedido_id, usuario_id):\n    with conexao.cursor() as cursor:\n        cursor.execute(\n            \"SELECT id, total FROM pedidos WHERE id = %s AND usuario_id = %s\",\n            (pedido_id, usuario_id),\n        )\n        return cursor.fetchone()" },
    { tipo: "p", texto: "Repare que o %s aqui não é a formatação de texto do Python: é um marcador do driver. Os valores vão no segundo argumento do execute. O erro mais comum é fazer a formatação antes, com % ou com uma f-string, e passar o resultado pronto." },
    { tipo: "codigo", linguagem: "python", legenda: "SQLAlchemy", texto: "from sqlalchemy import text\n\nresultado = sessao.execute(\n    text(\"SELECT id, total FROM pedidos WHERE id = :id\"),\n    {\"id\": pedido_id},\n)" },

    { tipo: "h3", texto: "Java" },
    { tipo: "codigo", linguagem: "java", legenda: "JDBC com PreparedStatement", texto: "String sql = \"SELECT id, total FROM pedidos WHERE id = ? AND usuario_id = ?\";\n\ntry (PreparedStatement comando = conexao.prepareStatement(sql)) {\n    comando.setLong(1, pedidoId);\n    comando.setLong(2, usuarioId);\n    try (ResultSet resultado = comando.executeQuery()) {\n        // ler o resultado\n    }\n}" },
    { tipo: "codigo", linguagem: "java", legenda: "Spring Data JPA com parâmetro nomeado", texto: "public interface PedidoRepository extends JpaRepository<Pedido, Long> {\n\n    @Query(\"SELECT p FROM Pedido p WHERE p.id = :id AND p.usuarioId = :usuarioId\")\n    Optional<Pedido> buscarDoUsuario(@Param(\"id\") Long id, @Param(\"usuarioId\") Long usuarioId);\n}" },
    { tipo: "p", texto: "Os métodos derivados do Spring Data, como findByIdAndUsuarioId, também geram consultas parametrizadas. O perigo aparece quando se escreve uma consulta nativa e se concatena a entrada nela:" },
    { tipo: "codigo", linguagem: "java", legenda: "Evite: consulta nativa com concatenação", texto: "// Vulnerável: o texto do usuário entra direto no comando\nentityManager.createNativeQuery(\n        \"SELECT * FROM pedidos WHERE cliente = '\" + cliente + \"'\");\n\n// Correto: parâmetro posicional\nentityManager.createNativeQuery(\"SELECT * FROM pedidos WHERE cliente = ?1\")\n        .setParameter(1, cliente);" },

    { tipo: "h3", texto: "Node e TypeScript" },
    { tipo: "codigo", linguagem: "typescript", legenda: "node-postgres: o marcador é $1, $2...", texto: "const resultado = await db.query(\n  \"SELECT id, total FROM pedidos WHERE id = $1 AND usuario_id = $2\",\n  [pedidoId, usuarioId],\n);" },
    { tipo: "p", texto: "O erro típico em JavaScript é usar um template literal, aquele texto entre crases, com ${...} dentro da consulta. A sintaxe é bonita e parece segura, mas o que chega ao banco é uma string já montada:" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Evite: template literal montando a consulta", texto: "// Vulnerável: o valor é inserido no texto antes de ir ao banco\nawait db.query(`SELECT * FROM pedidos WHERE cliente = '${cliente}'`);" },
    { tipo: "p", texto: "Alguns clientes de banco oferecem a sintaxe de template com proteção. O Prisma, por exemplo, tem o $queryRaw usado como template tagged, que transforma cada ${...} em parâmetro. Mas o $queryRawUnsafe, que recebe uma string comum, tem o mesmo risco de qualquer concatenação. O nome já avisa." },
    { tipo: "codigo", linguagem: "typescript", legenda: "Prisma", texto: "// Seguro: o template tagged vira consulta parametrizada\nconst pedidos = await prisma.$queryRaw`SELECT id, total FROM \"Pedido\" WHERE \"usuarioId\" = ${usuarioId}`;\n\n// Inseguro: string montada por concatenação\nconst ruim = await prisma.$queryRawUnsafe(\n  \"SELECT * FROM \\\"Pedido\\\" WHERE cliente = '\" + cliente + \"'\",\n);" },

    { tipo: "h", texto: "O que parâmetros não resolvem" },
    { tipo: "p", texto: "Parâmetros só valem para valores. Eles não podem substituir partes da estrutura do comando: nome de tabela, nome de coluna, direção de ordenação. Isso aparece o tempo todo em listagens com ordenação escolhida pelo usuário, como GET /pedidos?ordenar=total." },
    { tipo: "p", texto: "A solução é uma lista permitida (allowlist): o código define quais valores são aceitos e traduz a escolha do usuário para um valor fixo do próprio código." },
    { tipo: "codigo", linguagem: "typescript", legenda: "Ordenação com lista permitida", texto: "const COLUNAS_ORDENAVEIS: Record<string, string> = {\n  total: \"total\",\n  data: \"criado_em\",\n  status: \"status\",\n};\n\nfunction clausulaDeOrdenacao(pedido: string | undefined, direcao: string | undefined) {\n  const coluna = COLUNAS_ORDENAVEIS[pedido ?? \"\"] ?? \"criado_em\";\n  const sentido = direcao === \"asc\" ? \"ASC\" : \"DESC\";\n  return `ORDER BY ${coluna} ${sentido}`;\n}" },
    { tipo: "p", texto: "Note que a coluna e o sentido nunca vêm direto da entrada: o usuário só escolhe entre opções que o código conhece, e o resto cai em um padrão. Por isso aqui a interpolação é segura." },
    { tipo: "p", texto: "Outro cuidado é o LIKE. Mesmo parametrizado, um valor com % ou _ funciona como curinga. Isso não é injeção de SQL, mas pode permitir buscas mais amplas do que o desejado e consultas lentas. Se necessário, escape esses caracteres na busca." },

    { tipo: "h", texto: "Casos práticos que costumam quebrar a regra" },
    { tipo: "p", texto: "Na hora de escrever consultas reais, alguns casos fazem o iniciante abandonar o parâmetro e voltar para a concatenação. Vale conhecer a forma correta de cada um." },
    { tipo: "h3", texto: "Lista de valores com IN" },
    { tipo: "p", texto: "Você recebe uma lista de identificadores e quer buscar todos de uma vez. A tentação é juntar os números em um texto e colocar dentro do IN. A forma correta é gerar um marcador para cada valor, sem nunca colocar o valor no texto da consulta:" },
    { tipo: "codigo", linguagem: "python", legenda: "Um marcador por valor", texto: "def buscar_pedidos(conn, ids: list[int]):\n    if not ids:\n        return []\n    marcadores = \",\".join([\"?\"] * len(ids))   # \"?,?,?\"\n    consulta = f\"SELECT id, total FROM pedidos WHERE id IN ({marcadores})\"\n    return conn.execute(consulta, ids).fetchall()" },
    { tipo: "p", texto: "Aqui a f-string só monta uma sequência de interrogações, que não contém nada do usuário. Os valores vão no segundo argumento. O mesmo vale em Java com o NamedParameterJdbcTemplate, que expande uma lista sozinho:" },
    { tipo: "codigo", linguagem: "java", legenda: "Spring: a lista vira vários parâmetros", texto: "String sql = \"SELECT id, total FROM pedidos WHERE id IN (:ids)\";\n\nList<Pedido> pedidos = jdbc.query(\n        sql, Map.of(\"ids\", ids), pedidoMapper);" },
    { tipo: "h3", texto: "Paginação com LIMIT e OFFSET" },
    { tipo: "p", texto: "Alguns drivers e bancos aceitam parâmetros em LIMIT e OFFSET e outros não. Quando não aceitam, converta para inteiro, limite o intervalo e só então insira no texto. Um número validado não carrega comando nenhum:" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Número validado, tamanho limitado", texto: "function paginacao(pagina: unknown, tamanho: unknown) {\n  const p = Math.max(0, Number.parseInt(String(pagina), 10) || 0);\n  const t = Math.min(100, Math.max(1, Number.parseInt(String(tamanho), 10) || 20));\n  return { limite: t, deslocamento: p * t };\n}" },
    { tipo: "p", texto: "Limitar o tamanho máximo da página tem uma segunda função: impede que um pedido com tamanho=1000000 derrube o banco, o que é um problema de disponibilidade." },
    { tipo: "h3", texto: "Inserções em lote" },
    { tipo: "p", texto: "Para gravar muitas linhas, o erro é montar um INSERT gigante com todos os valores concatenados. Use o recurso de lote do driver (executemany no Python, batch no JDBC), que reaproveita a mesma consulta parametrizada para cada linha, e costuma ser mais rápido também." },
    { tipo: "h3", texto: "Busca por texto" },
    { tipo: "p", texto: "Para pesquisar com LIKE, o curinga % faz parte do valor, não da consulta: passe o valor já com os curingas, como um parâmetro, em vez de escrever LIKE '%' + termo + '%'. Se quiser que % e _ digitados pelo usuário sejam tratados como texto comum, escape-os antes e declare o caractere de escape na cláusula ESCAPE." },
    { tipo: "p", texto: "O fio condutor é sempre o mesmo: a estrutura da consulta é escrita pelo código, e tudo o que vem de fora entra como valor. Quando você sentir vontade de juntar texto em uma consulta, pare e pergunte se o que está sendo juntado vem de uma lista fixa do seu código ou de algum lugar que alguém de fora controla." },

    { tipo: "h", texto: "ORMs ajudam, mas não protegem de tudo" },
    { tipo: "p", texto: "Um ORM como JPA/Hibernate, Django ORM, SQLAlchemy ou Prisma gera consultas parametrizadas na maior parte do tempo. Isso é uma proteção real e uma boa razão para usá-los. Os problemas costumam aparecer nas exceções:" },
    { tipo: "lista", itens: [
      "Consultas nativas ou brutas montadas com concatenação (createNativeQuery, raw, $queryRawUnsafe, text com f-string).",
      "Nomes de campos de ordenação ou de filtro montados com a entrada do usuário.",
      "Passar o corpo da requisição inteiro como filtro, em vez de escolher campos conhecidos.",
    ] },
    { tipo: "codigo", linguagem: "python", legenda: "Django: raw() com parâmetros", texto: "# Seguro: os valores vão separados\nPedido.objects.raw(\n    \"SELECT * FROM app_pedido WHERE cliente_id = %s\", [cliente_id]\n)\n\n# Inseguro: a formatação acontece antes\nPedido.objects.raw(f\"SELECT * FROM app_pedido WHERE cliente_id = {cliente_id}\")" },

    { tipo: "h3", texto: "O primo NoSQL" },
    { tipo: "p", texto: "Bancos como o MongoDB não usam SQL, mas têm o mesmo tipo de problema quando a entrada é tratada como estrutura. Em um servidor Node com Mongoose, este login parece inocente:" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Vulnerável a injeção de operadores", texto: "// Se o corpo for { \"email\": \"ana@exemplo.com\", \"senha\": { \"$ne\": null } },\n// a condição vira \"senha diferente de nula\", que quase sempre é verdadeira.\nconst usuario = await Usuario.findOne({\n  email: req.body.email,\n  senha: req.body.senha,\n});" },
    { tipo: "p", texto: "O problema é aceitar que um campo que deveria ser texto chegue como objeto. A defesa é validar o tipo e o formato do corpo antes de usá-lo (com uma biblioteca de validação como Zod, Joi ou class-validator), e nunca comparar senha em texto na consulta: busque o usuário pelo e-mail e confira o hash da senha no código." },

    { tipo: "h", texto: "Defesa em profundidade" },
    { tipo: "p", texto: "A consulta parametrizada é a camada principal, mas não a única." },
    { tipo: "h3", texto: "Validação de entrada" },
    { tipo: "p", texto: "Valide tipo, tamanho e formato no limite do sistema. Se um identificador deve ser um número inteiro, rejeite qualquer coisa que não seja. Se um e-mail tem no máximo 254 caracteres, imponha esse limite. Validação não substitui a parametrização, mas barra muita coisa estranha logo na entrada e deixa o código mais previsível." },
    { tipo: "h3", texto: "Menor privilégio no banco" },
    { tipo: "p", texto: "A conta que a aplicação usa para falar com o banco não precisa ser dona do esquema nem ter permissão para apagar tabelas. Crie uma conta só com o necessário (SELECT, INSERT, UPDATE e DELETE nas tabelas usadas) e use contas separadas para migrações e relatórios. Se uma injeção acontecer, o estrago fica limitado." },
    { tipo: "h3", texto: "Erros que não revelam o banco" },
    { tipo: "p", texto: "Nunca devolva ao cliente a mensagem de erro do banco. Ela mostra nomes de tabelas, colunas e trechos da consulta, que ajudam quem está investigando. Registre o detalhe no log e responda com uma mensagem genérica." },
    { tipo: "h3", texto: "O que não é defesa suficiente" },
    { tipo: "lista", itens: [
      "Filtrar palavras ou caracteres proibidos: é contornável e quebra entradas legítimas.",
      "Escapar manualmente as aspas: é fácil de errar e depende do banco.",
      "Confiar em um firewall de aplicação web (WAF) como única proteção: ele ajuda como camada extra, mas não conserta a consulta insegura.",
      "Achar que procedimentos armazenados são seguros por natureza: se eles montam SQL por concatenação por dentro, o problema continua.",
    ] },

    { tipo: "h", texto: "Como testar" },
    { tipo: "p", texto: "Teste automatizado é a melhor forma de garantir que uma correção não volte atrás. A ideia é chamar a função com entradas maliciosas e conferir que nada de errado acontece. Este teste em pytest roda sozinho, com um banco SQLite em memória:" },
    { tipo: "codigo", linguagem: "python", legenda: "test_injecao.py", texto: "import sqlite3\n\n\ndef buscar_usuario(conn, email):\n    cursor = conn.execute(\n        \"SELECT id, email FROM usuarios WHERE email = ?\", (email,)\n    )\n    return cursor.fetchone()\n\n\ndef criar_banco():\n    conn = sqlite3.connect(\":memory:\")\n    conn.execute(\"CREATE TABLE usuarios (id INTEGER PRIMARY KEY, email TEXT)\")\n    conn.execute(\"INSERT INTO usuarios (email) VALUES ('ana@exemplo.com')\")\n    return conn\n\n\ndef test_entrada_maliciosa_nao_vira_comando():\n    conn = criar_banco()\n\n    assert buscar_usuario(conn, \"' OR '1'='1\") is None\n    assert buscar_usuario(conn, \"x'; DROP TABLE usuarios; --\") is None\n    # a tabela continua existindo\n    assert buscar_usuario(conn, \"ana@exemplo.com\") is not None" },
    { tipo: "p", texto: "O teste prova três coisas: a entrada maliciosa é tratada como um e-mail comum (que não existe), um segundo comando embutido não é executado, e o dado legítimo continua sendo encontrado. Se alguém trocar o ? por concatenação, o primeiro assert falha." },
    { tipo: "p", texto: "Além dos testes, ajudam as ferramentas de análise estática, que procuram o padrão de concatenação em chamadas de banco. Para Java, o SpotBugs com o plugin Find Security Bugs; para várias linguagens, o Semgrep e o CodeQL." },

    { tipo: "h", texto: "Revisando código: o que procurar" },
    { tipo: "numerada", itens: [
      "Qualquer chamada de execução de consulta (execute, query, createNativeQuery, raw, $queryRawUnsafe) recebendo uma string montada com +, f-string, format ou template literal.",
      "Nomes de tabela, coluna ou ordenação vindos de parâmetros da requisição sem lista permitida.",
      "Filtros montados a partir do corpo inteiro da requisição.",
      "Mensagens de erro de banco devolvidas ao cliente.",
      "A conta de banco da aplicação com permissões de administrador.",
    ] },
  ],
  exercicios: [
    "Procure no seu projeto toda chamada que executa SQL. Alguma recebe texto montado por concatenação? Corrija e escreva um teste como o do artigo.",
    "Implemente uma listagem com ordenação escolhida pelo usuário usando lista permitida, e escreva testes para uma coluna inválida e para uma direção inválida.",
    "Crie, no banco de desenvolvimento, uma conta só com SELECT, INSERT, UPDATE e DELETE nas tabelas da aplicação e rode o projeto com ela. O que quebrou?",
    "Rode o Semgrep ou o CodeQL no seu repositório e leia os resultados de segurança. Quais eram falsos positivos e por quê?",
  ],
  referencias: [
    { titulo: "OWASP: SQL Injection Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    { titulo: "OWASP: Query Parameterization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Query_Parameterization_Cheat_Sheet.html" },
    { titulo: "OWASP: Injection Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_Cheat_Sheet.html" },
    { titulo: "OWASP: Input Validation Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html" },
  ],
};
