import type { Aula } from "./tipos";

export const AULA_NAVEGADOR: Aula = {
  slug: "seguranca-no-navegador-xss-csrf-cors-e-cabecalhos",
  titulo: "Segurança no navegador: XSS, CSRF, CORS e cabeçalhos de segurança",
  resumo: "O que cada sigla significa, por que o navegador se comporta assim e como se proteger sem decorar receitas.",
  trilha: "seguranca",
  nivel: "Intermediário",
  leitura: "24 min",
  preRequisitos: [
    "Saber o que são cookies e cabeçalhos HTTP.",
    "Ter feito uma página que chama uma API com fetch ou formulário.",
    "Ter lido o artigo sobre autenticação e autorização desta trilha ajuda, mas não é obrigatório.",
  ],
  pontosChave: [
    "A política de mesma origem é a base de tudo: o navegador isola sites diferentes uns dos outros.",
    "XSS é código de terceiros rodando na sua página. A defesa é tratar a saída de dados conforme o contexto, e usar CSP como segunda camada.",
    "CSRF é o navegador enviando cookies sem a pessoa querer. A defesa é SameSite, token e conferência de origem.",
    "CORS não protege o servidor: ele só relaxa uma regra do navegador. Configure com lista de origens, nunca com asterisco e credenciais.",
    "Cabeçalhos de segurança são camadas baratas e valem a pena em todo projeto.",
  ],
  blocos: [
    { tipo: "p", texto: "A web foi pensada para que você visite sites que não conhece sem que eles consigam mexer no que você faz em outros. Quase tudo o que o navegador faz em nome da segurança nasce desse princípio. Entendê-lo transforma XSS, CSRF e CORS de siglas soltas em consequências de uma mesma ideia." },

    { tipo: "h", texto: "A política de mesma origem" },
    { tipo: "p", texto: "Uma origem é a combinação de três partes: o esquema (http ou https), o servidor (o domínio) e a porta. Duas URLs têm a mesma origem se as três coincidem." },
    { tipo: "tabela", legenda: "Comparando com https://app.exemplo.com", cabecalho: ["URL", "Mesma origem?", "Motivo"], linhas: [
      ["https://app.exemplo.com/pedidos", "Sim", "Só o caminho muda."],
      ["http://app.exemplo.com", "Não", "Esquema diferente."],
      ["https://api.exemplo.com", "Não", "Servidor diferente."],
      ["https://app.exemplo.com:8443", "Não", "Porta diferente."],
    ] },
    { tipo: "p", texto: "A política de mesma origem (same-origin policy) diz, em essência: um script de uma origem não pode ler as respostas de outra origem. Se você está em um site malicioso, o script dele não consegue ler o conteúdo da sua conta de banco aberta em outra aba." },
    { tipo: "alerta", titulo: "O que a política não impede", texto: "Ela impede a leitura da resposta, mas não impede que o navegador envie a requisição. Um site qualquer pode fazer o seu navegador enviar uma requisição para outro site, e o navegador ainda anexa os cookies desse outro site. Essa brecha é a origem do CSRF, visto mais abaixo." },

    { tipo: "h", texto: "XSS: quando o código de outra pessoa roda na sua página" },
    { tipo: "p", texto: "O XSS (Cross-Site Scripting) acontece quando a aplicação mostra dados controlados por alguém (um comentário, um nome, um parâmetro da URL) sem tratá-los, e o navegador interpreta esse texto como HTML ou JavaScript. A partir daí, o script do atacante roda com a origem e os privilégios do seu site." },
    { tipo: "h3", texto: "O que um XSS consegue" },
    { tipo: "lista", itens: [
      "Ler dados da página que a pessoa está vendo e enviá-los para fora.",
      "Fazer requisições em nome do usuário, com a sessão dele: trocar o e-mail, fazer uma compra, apagar dados.",
      "Roubar tokens guardados em localStorage e, em alguns casos, cookies sem HttpOnly.",
      "Alterar a página para enganar (um formulário de login falso, por exemplo).",
    ] },
    { tipo: "p", texto: "Note que um cookie HttpOnly impede o roubo do cookie, mas não impede o script de agir em nome do usuário. Por isso a defesa não pode parar na flag do cookie." },
    { tipo: "h3", texto: "Os três tipos" },
    { tipo: "lista", itens: [
      "Armazenado: o dado malicioso fica salvo (um comentário, um perfil) e é exibido para todo mundo que abrir aquela página.",
      "Refletido: o dado vem na requisição (um parâmetro de busca) e a resposta o devolve na página. O atacante precisa fazer a vítima abrir um link.",
      "Baseado em DOM: o problema está no JavaScript do navegador, que pega um dado (da URL, por exemplo) e o escreve na página de forma insegura, sem o servidor participar.",
    ] },
    { tipo: "h3", texto: "A causa: misturar dado e marcação" },
    { tipo: "p", texto: "É a mesma raiz da injeção de SQL: texto do usuário virando parte de um comando, aqui o HTML. Veja um exemplo de DOM:" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Inseguro × seguro no DOM", texto: "// Inseguro: o navegador interpreta o texto como HTML\nelemento.innerHTML = \"Olá, \" + nomeDoUsuario;\n\n// Seguro: o texto é tratado só como texto\nelemento.textContent = \"Olá, \" + nomeDoUsuario;" },
    { tipo: "p", texto: "Se nomeDoUsuario contiver uma tag com um manipulador de evento, o innerHTML a executa. O textContent a mostra literalmente na tela, sem executar." },
    { tipo: "h3", texto: "A defesa principal: tratar a saída conforme o contexto" },
    { tipo: "p", texto: "O que é seguro depende de onde o dado será colocado. O mesmo texto precisa de tratamentos diferentes em cada contexto:" },
    { tipo: "tabela", cabecalho: ["Contexto", "Exemplo", "Tratamento"], linhas: [
      ["Texto dentro do HTML", "<p>NOME</p>", "Codificar < > & como entidades HTML."],
      ["Atributo", "<input value=\"NOME\">", "Codificar e sempre usar aspas no atributo."],
      ["URL", "<a href=\"URL\">", "Validar o esquema (só http e https) e codificar. Cuidado com javascript:."],
      ["JavaScript", "<script>var x = \"NOME\"</script>", "Evitar. Passar dados como JSON ou atributos data-*."],
    ] },
    { tipo: "p", texto: "Na prática, você não codifica na mão: usa um framework que faz o tratamento automático e evita as saídas que o desligam." },
    { tipo: "codigo", linguagem: "typescript", legenda: "React: seguro por padrão, perigoso se desligado", texto: "// Seguro: o React escapa o valor\nreturn <p>{comentario.texto}</p>;\n\n// Perigoso: o nome da propriedade já avisa\nreturn <p dangerouslySetInnerHTML={{ __html: comentario.texto }} />;" },
    { tipo: "codigo", linguagem: "html", legenda: "Templates: o escape automático e como desligá-lo", texto: "<!-- Jinja2 (Flask, FastAPI): escapa por padrão -->\n<p>{{ comentario }}</p>\n<!-- Perigoso: |safe desliga o escape -->\n<p>{{ comentario|safe }}</p>\n\n<!-- Thymeleaf (Spring): th:text escapa, th:utext não -->\n<p th:text=\"${comentario}\">...</p>\n<p th:utext=\"${comentario}\">...</p>" },
    { tipo: "h3", texto: "Quando você precisa mesmo de HTML do usuário" },
    { tipo: "p", texto: "Editores de texto rico guardam HTML. Nesse caso, não escreva o seu próprio filtro: use uma biblioteca de sanitização mantida, como o DOMPurify no navegador (ou no Node, com um DOM simulado), que remove o que é perigoso e deixa o que é permitido. Prefira formatos mais restritos, como Markdown, convertido e sanitizado." },
    { tipo: "h3", texto: "Segunda camada: a política de segurança de conteúdo (CSP)" },
    { tipo: "p", texto: "A CSP é um cabeçalho que diz ao navegador de onde a página pode carregar scripts, estilos, imagens e outras coisas. Mesmo que um XSS consiga inserir um script, a política pode impedir que ele execute ou que envie dados para um servidor não autorizado." },
    { tipo: "codigo", linguagem: "http", legenda: "Uma política restritiva como ponto de partida", texto: "Content-Security-Policy: default-src 'self'; script-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" },
    { tipo: "p", texto: "O 'self' permite recursos da própria origem. Evite 'unsafe-inline' e 'unsafe-eval', que desfazem boa parte da proteção contra XSS. Muitos projetos começam com a CSP em modo de relatório (Content-Security-Policy-Report-Only) para ver o que quebraria antes de aplicar." },

    { tipo: "h", texto: "CSRF: o navegador enviando cookies sem a pessoa querer" },
    { tipo: "p", texto: "O CSRF (Cross-Site Request Forgery) explora uma característica do navegador: ao fazer uma requisição para um site, ele anexa automaticamente os cookies daquele site, não importa quem iniciou a requisição." },
    { tipo: "p", texto: "Imagine que você está logado em um site de banco. Você abre, em outra aba, uma página maliciosa que contém um formulário escondido apontando para a rota de transferência do banco, enviado automaticamente. O navegador envia o formulário e anexa o cookie de sessão do banco. Para o banco, a requisição parece legítima: veio de um navegador autenticado." },
    { tipo: "alerta", titulo: "Quando o CSRF é possível", texto: "Precisa de três coisas ao mesmo tempo: uma ação que altera estado, autenticação feita por cookies (que o navegador anexa sozinho) e nenhum parâmetro imprevisível que o atacante não consiga conhecer. APIs que autenticam por um cabeçalho Authorization preenchido pelo próprio código não têm o problema, porque o navegador não anexa esse cabeçalho sozinho." },
    { tipo: "h3", texto: "As defesas" },
    { tipo: "numerada", itens: [
      "Cookies SameSite: com Lax ou Strict, o navegador não envia o cookie em requisições originadas em outro site (com a exceção de navegação por link, no Lax). É a defesa mais simples e hoje o padrão de vários navegadores.",
      "Token anti-CSRF: o servidor gera um valor aleatório ligado à sessão, entrega à página legítima e exige que ele volte em toda requisição que altera estado (em um cabeçalho ou campo). Um site de fora não consegue ler o valor, por causa da política de mesma origem.",
      "Conferir a origem: validar os cabeçalhos Origin ou Referer da requisição contra uma lista de origens esperadas.",
      "Exigir um cabeçalho personalizado em chamadas de API (como X-Requested-With). Um formulário de outro site não consegue enviar cabeçalhos personalizados sem um preflight do CORS.",
      "Nunca alterar estado com GET. Navegação, imagens e prefetch usam GET, e um link malicioso poderia disparar a ação.",
    ] },
    { tipo: "p", texto: "O projeto Koda, por exemplo, combina duas dessas camadas: o cookie de sessão é SameSite=Lax e toda requisição que altera estado precisa levar um token CSRF. Sem o token, mesmo com a sessão válida, a resposta é 403." },
    { tipo: "codigo", linguagem: "java", legenda: "Spring Security: o CSRF vem ligado", texto: "// Em aplicações com sessão, o Spring Security já exige o token.\n// Desligar é uma decisão consciente, só razoável em APIs sem cookies:\nhttp.csrf(csrf -> csrf.disable());   // cuidado" },
    { tipo: "alerta", titulo: "Desligar o CSRF 'porque dá erro'", texto: "É uma das respostas mais comuns (e perigosas) de fóruns: o formulário falhava com 403, então desligaram a proteção. Antes de desligar, entenda se a aplicação usa cookies para autenticar. Se usa, o correto é enviar o token, não remover a defesa." },

    { tipo: "h", texto: "CORS: relaxando a política de mesma origem" },
    { tipo: "p", texto: "Às vezes o front-end e a API ficam em origens diferentes (app.exemplo.com e api.exemplo.com) e você quer que o navegador permita a leitura da resposta. O CORS (Cross-Origin Resource Sharing) é o mecanismo para isso: o servidor declara, por cabeçalhos, quais origens podem ler as respostas." },
    { tipo: "h3", texto: "Como funciona" },
    { tipo: "numerada", itens: [
      "O navegador envia a requisição com o cabeçalho Origin.",
      "Para requisições \"não simples\" (métodos como PUT e DELETE, ou cabeçalhos personalizados), ele antes faz uma requisição de pré-verificação, o preflight, com o método OPTIONS.",
      "O servidor responde com Access-Control-Allow-Origin e outros cabeçalhos dizendo o que permite.",
      "Se a resposta autoriza, o navegador faz a requisição de verdade e entrega o resultado ao script. Se não, ele bloqueia a leitura e mostra o famoso erro de CORS no console.",
    ] },
    { tipo: "h3", texto: "O que o CORS não é" },
    { tipo: "p", texto: "O CORS é uma regra do navegador a favor do usuário, não uma proteção do servidor. Uma ferramenta de linha de comando, como o curl, ignora o CORS completamente. Por isso o CORS não substitui autenticação e autorização no servidor: ele só decide se o JavaScript de uma página pode ler a resposta." },
    { tipo: "h3", texto: "Erros comuns de configuração" },
    { tipo: "lista", itens: [
      "Access-Control-Allow-Origin: * junto de credenciais. O navegador recusa essa combinação, e a solução errada é refletir o cabeçalho Origin recebido, o que na prática libera qualquer site.",
      "Refletir qualquer origem sem verificar. Sempre compare com uma lista fixa de origens permitidas.",
      "Permitir todos os métodos e cabeçalhos \"por via das dúvidas\".",
      "Liberar a origem null, que pode ser forjada por páginas locais e iframes isolados.",
    ] },
    { tipo: "codigo", linguagem: "typescript", legenda: "Express com a biblioteca cors", texto: "import cors from \"cors\";\n\napp.use(\n  cors({\n    origin: [\"https://app.exemplo.com\"],\n    methods: [\"GET\", \"POST\", \"PUT\", \"DELETE\"],\n    credentials: true,\n  }),\n);" },
    { tipo: "codigo", linguagem: "python", legenda: "FastAPI", texto: "from fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=[\"https://app.exemplo.com\"],\n    allow_methods=[\"GET\", \"POST\", \"PUT\", \"DELETE\"],\n    allow_headers=[\"Content-Type\", \"Authorization\"],\n    allow_credentials=True,\n)" },
    { tipo: "codigo", linguagem: "java", legenda: "Spring", texto: "@Configuration\npublic class CorsConfig implements WebMvcConfigurer {\n\n    @Override\n    public void addCorsMappings(CorsRegistry registry) {\n        registry.addMapping(\"/api/**\")\n                .allowedOrigins(\"https://app.exemplo.com\")\n                .allowedMethods(\"GET\", \"POST\", \"PUT\", \"DELETE\")\n                .allowCredentials(true);\n    }\n}" },
    { tipo: "dica", titulo: "Um jeito de evitar o CORS", texto: "Se o front-end e a API forem servidos pela mesma origem (por exemplo, o servidor do front-end repassa as chamadas /api para o backend), não há CORS nenhum para configurar. É o que o projeto Koda faz em desenvolvimento e em produção: o Next.js encaminha as requisições /api, e o navegador só enxerga uma origem." },

    { tipo: "h", texto: "Cabeçalhos de segurança" },
    { tipo: "p", texto: "Além da CSP, existem cabeçalhos simples que pedem ao navegador para ligar proteções extras. São baratos de adicionar e valem em quase todo projeto." },
    { tipo: "tabela", cabecalho: ["Cabeçalho", "O que faz", "Valor típico"], linhas: [
      ["Strict-Transport-Security", "Obriga o navegador a usar HTTPS nesse site, por um tempo.", "max-age=31536000; includeSubDomains"],
      ["X-Content-Type-Options", "Impede o navegador de adivinhar o tipo de um arquivo, o que evita que texto seja executado como script.", "nosniff"],
      ["Content-Security-Policy (frame-ancestors)", "Controla quem pode embutir a sua página em um iframe, evitando o clickjacking.", "frame-ancestors 'none'"],
      ["X-Frame-Options", "Versão antiga do controle acima, mantida por compatibilidade.", "DENY"],
      ["Referrer-Policy", "Limita quanto da URL de origem vai para outros sites.", "strict-origin-when-cross-origin"],
      ["Permissions-Policy", "Desliga recursos do navegador que você não usa (câmera, geolocalização).", "geolocation=(), camera=()"],
      ["Cache-Control", "Evita que respostas com dados pessoais fiquem em cache.", "no-store"],
    ] },
    { tipo: "codigo", linguagem: "typescript", legenda: "Express com helmet", texto: "import helmet from \"helmet\";\n\n// Liga um conjunto razoável de cabeçalhos de uma vez\napp.use(helmet());" },
    { tipo: "p", texto: "O helmet configura vários cabeçalhos com valores padrão sensatos. Em Spring Security, a maior parte deles já vem ligada por padrão; no Python, existem middlewares equivalentes, e em qualquer caso você pode adicionar os cabeçalhos no servidor web ou no proxy reverso." },

    { tipo: "h", texto: "Como testar e conferir" },
    { tipo: "p", texto: "Cabeçalhos são fáceis de testar, e um teste evita que alguém os remova sem querer em uma refatoração:" },
    { tipo: "codigo", linguagem: "typescript", legenda: "Teste com supertest", texto: "import request from \"supertest\";\n\nit(\"envia os cabeçalhos de segurança\", async () => {\n  const resposta = await request(app).get(\"/\");\n\n  expect(resposta.headers[\"x-content-type-options\"]).toBe(\"nosniff\");\n  expect(resposta.headers[\"content-security-policy\"]).toContain(\"default-src\");\n});\n\nit(\"recusa origens que não estão na lista\", async () => {\n  const resposta = await request(app)\n    .get(\"/api/pedidos\")\n    .set(\"Origin\", \"https://site-malicioso.exemplo\");\n\n  expect(resposta.headers[\"access-control-allow-origin\"]).toBeUndefined();\n});" },
    { tipo: "p", texto: "Para uma conferência rápida de um site publicado, existem ferramentas gratuitas, como o Mozilla Observatory e o securityheaders.com, que leem os cabeçalhos e dão uma nota com sugestões. Nas ferramentas do desenvolvedor do navegador, a aba Rede mostra os cabeçalhos de cada resposta, e o console mostra violações da CSP e erros de CORS." },

    { tipo: "h", texto: "Resumo: três problemas, três defesas" },
    { tipo: "tabela", cabecalho: ["", "XSS", "CSRF", "CORS mal configurado"], linhas: [
      ["O que acontece", "Código de terceiros roda na sua página.", "Uma ação é disparada por outro site com a sessão da vítima.", "Um site de fora consegue ler respostas que não deveria."],
      ["Defesa principal", "Tratar a saída conforme o contexto.", "Cookies SameSite e token anti-CSRF.", "Lista fixa de origens permitidas."],
      ["Camada extra", "CSP e cookies HttpOnly.", "Conferir Origin e exigir cabeçalho próprio.", "Autenticação e autorização no servidor."],
    ] },
  ],
  exercicios: [
    "No seu projeto, procure usos de innerHTML, dangerouslySetInnerHTML, |safe ou th:utext. Para cada um, descreva de onde vem o dado e se pode ser controlado por alguém de fora.",
    "Abra a aba Rede das ferramentas do navegador e liste os cabeçalhos de segurança que o seu sistema envia. Quais faltam?",
    "Configure uma CSP em modo de relatório (Report-Only) e leia no console o que ela acusaria.",
    "Tente fazer uma requisição POST para a sua API a partir de um arquivo HTML aberto de outro lugar. O que o navegador permite? O que o servidor recusa?",
    "Escreva um teste que confirma que uma requisição sem token CSRF (ou de uma origem não permitida) é recusada.",
  ],
  referencias: [
    { titulo: "MDN: Política de mesma origem (em inglês)", url: "https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Same-origin_policy" },
    { titulo: "MDN: CORS", url: "https://developer.mozilla.org/pt-BR/docs/Web/HTTP/CORS" },
    { titulo: "MDN: Content Security Policy", url: "https://developer.mozilla.org/pt-BR/docs/Web/HTTP/CSP" },
    { titulo: "OWASP: XSS Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" },
    { titulo: "OWASP: CSRF Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html" },
    { titulo: "OWASP: HTTP Headers Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html" },
  ],
};
